// pebaspro-master-administrativo/src/pages/Vagas.tsx
import React, { useState, useEffect, useMemo } from 'react';
import { Search, Filter, Briefcase, MapPin, Building2, Clock, CheckCircle2, XCircle, MoreVertical, Eye, Play, Pause, Star } from 'lucide-react';
import { Modal } from '../components/ui/Modal';
import { Pagination } from '../components/ui/Pagination';
import { EmptyState } from '../components/ui/EmptyState';
import { usePermissions } from '../hooks/usePermissions';
import { useAudit } from '../hooks/useAudit';

const mockVagas = Array.from({ length: 30 }, (_, i) => ({
  id: i + 1,
  titulo: `Vaga de Teste ${i + 1}`,
  empresa: `Empresa ${Math.floor(i / 3) + 1} Ltda`,
  local: i % 3 === 0 ? 'Remoto' : i % 2 === 0 ? 'São Paulo, SP' : 'Híbrido',
  status: i % 5 === 0 ? 'encerrada' : i % 4 === 0 ? 'pausada' : 'aberta',
  tipo: i % 3 === 0 ? 'PJ' : 'CLT',
  candidatos: Math.floor(Math.random() * 150),
  dataCriacao: `1${i % 9}/04/2026`,
  destaque: i % 7 === 0
}));

export default function Vagas() {
  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [isLoading, setIsLoading] = useState(true);
  const [selectedVaga, setSelectedVaga] = useState<any>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const { canPerformAction } = usePermissions();
  const { logAction } = useAudit();
  const itemsPerPage = 10;

  useEffect(() => {
    const timer = setTimeout(() => setIsLoading(false), 500);
    return () => clearTimeout(timer);
  }, []);

  const filteredVagas = useMemo(() => {
    return mockVagas.filter(v =>
      v.titulo.toLowerCase().includes(searchTerm.toLowerCase()) ||
      v.empresa.toLowerCase().includes(searchTerm.toLowerCase()) ||
      v.local.toLowerCase().includes(searchTerm.toLowerCase())
    );
  }, [searchTerm]);

  const totalPages = Math.ceil(filteredVagas.length / itemsPerPage);
  const paginatedVagas = filteredVagas.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  useEffect(() => {
    setCurrentPage(1);
  }, [searchTerm]);

  const handleViewDetails = (vaga: any) => {
    setSelectedVaga(vaga);
    setIsModalOpen(true);
    logAction('view_vaga_details', 'vagas', { vagaId: vaga.id });
  };

  const handleToggleStatus = (vaga: any, newStatus: string) => {
    if (!canPerformAction('edit', 'vagas')) {
      alert('Você não tem permissão para realizar esta ação.');
      return;
    }
    logAction('change_vaga_status', 'vagas', { vagaId: vaga.id, newStatus });
    alert(`Status da vaga "${vaga.titulo}" alterado para ${newStatus}. (Simulação)`);
  };

  const handleToggleDestaque = (vaga: any) => {
    if (!canPerformAction('edit', 'vagas')) return;
    const newDestaque = !vaga.destaque;
    logAction('toggle_vaga_destaque', 'vagas', { vagaId: vaga.id, destaque: newDestaque });
    alert(`Destaque da vaga "${vaga.titulo}" ${newDestaque ? 'ativado' : 'removido'}. (Simulação)`);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-gray-900">Gestão de Vagas</h1>
          <p className="mt-1 text-sm text-gray-500">
            Acompanhe e modere todas as vagas publicadas pelas empresas na plataforma.
          </p>
        </div>
        <div className="flex items-center gap-2">
          {canPerformAction('create', 'vagas') && (
            <button className="inline-flex items-center gap-2 rounded-md bg-primary-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-primary-500">
              Nova Vaga (Admin)
            </button>
          )}
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        <div className="overflow-hidden rounded-xl bg-white px-4 py-5 shadow-sm border border-gray-100">
          <dt className="truncate text-sm font-medium text-gray-500">Total de Vagas</dt>
          <dd className="mt-2 text-3xl font-semibold tracking-tight text-gray-900">3.456</dd>
        </div>
        <div className="overflow-hidden rounded-xl bg-white px-4 py-5 shadow-sm border border-gray-100">
          <dt className="truncate text-sm font-medium text-gray-500">Vagas Ativas</dt>
          <dd className="mt-2 text-3xl font-semibold tracking-tight text-green-600">1.245</dd>
        </div>
        <div className="overflow-hidden rounded-xl bg-white px-4 py-5 shadow-sm border border-gray-100">
          <dt className="truncate text-sm font-medium text-gray-500">Vagas Premium</dt>
          <dd className="mt-2 text-3xl font-semibold tracking-tight text-purple-600">342</dd>
        </div>
        <div className="overflow-hidden rounded-xl bg-white px-4 py-5 shadow-sm border border-gray-100">
          <dt className="truncate text-sm font-medium text-gray-500">Candidaturas (Mês)</dt>
          <dd className="mt-2 text-3xl font-semibold tracking-tight text-blue-600">18.492</dd>
        </div>
      </div>

      <div className="flex flex-col sm:flex-row gap-4 items-center justify-between bg-white p-4 rounded-xl shadow-sm border border-gray-100">
        <div className="relative w-full sm:max-w-md">
          <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
            <Search className="h-4 w-4 text-gray-400" />
          </div>
          <input
            type="text"
            className="block w-full rounded-md border-0 py-1.5 pl-10 pr-3 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-600 sm:text-sm sm:leading-6"
            placeholder="Buscar por título, empresa ou local..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
        </div>
        <div className="flex gap-2 w-full sm:w-auto">
          <button className="inline-flex items-center gap-2 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
            <Filter className="h-4 w-4 text-gray-500" />
            Filtros Avançados
          </button>
        </div>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        {isLoading ? (
          <div className="p-12 text-center text-gray-500">Carregando dados...</div>
        ) : filteredVagas.length === 0 ? (
          <EmptyState
            title="Nenhuma vaga encontrada"
            description={`Não encontramos resultados para "${searchTerm}".`}
          />
        ) : (
          <>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Vaga</th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Empresa</th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Status</th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Candidatos</th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Data Criação</th>
                    <th scope="col" className="relative py-3.5 pl-3 pr-4 sm:pr-6">
                      <span className="sr-only">Ações</span>
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200 bg-white">
                  {paginatedVagas.map((vaga) => (
                    <tr key={vaga.id} className="hover:bg-gray-50">
                      <td className="whitespace-nowrap py-4 pl-4 pr-3 sm:pl-6">
                        <div className="flex items-center">
                          <div className="h-10 w-10 flex-shrink-0 rounded-md bg-blue-50 flex items-center justify-center border border-blue-100">
                            <Briefcase className="h-5 w-5 text-blue-600" />
                          </div>
                          <div className="ml-4">
                            <div className="font-medium text-gray-900 flex items-center gap-2">
                              {vaga.titulo}
                              {vaga.destaque && <Star className="h-3 w-3 text-yellow-400 fill-current" title="Vaga Destacada" />}
                            </div>
                            <div className="text-sm text-gray-500 flex items-center gap-2 mt-0.5">
                              <span className="flex items-center gap-1"><MapPin className="h-3 w-3" /> {vaga.local}</span>
                              <span>&bull;</span>
                              <span>{vaga.tipo}</span>
                            </div>
                          </div>
                        </div>
                      </td>
                      <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                        <div className="flex items-center gap-1.5">
                          <Building2 className="h-4 w-4 text-gray-400" />
                          {vaga.empresa}
                        </div>
                      </td>
                      <td className="whitespace-nowrap px-3 py-4 text-sm">
                        {vaga.status === 'aberta' && (
                          <span className="inline-flex items-center gap-1.5 rounded-full bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
                            <CheckCircle2 className="h-3.5 w-3.5" />
                            Aberta
                          </span>
                        )}
                        {vaga.status === 'pausada' && (
                          <span className="inline-flex items-center gap-1.5 rounded-full bg-yellow-50 px-2 py-1 text-xs font-medium text-yellow-800 ring-1 ring-inset ring-yellow-600/20">
                            <Clock className="h-3.5 w-3.5" />
                            Pausada
                          </span>
                        )}
                        {vaga.status === 'encerrada' && (
                          <span className="inline-flex items-center gap-1.5 rounded-full bg-gray-50 px-2 py-1 text-xs font-medium text-gray-600 ring-1 ring-inset ring-gray-500/10">
                            <XCircle className="h-3.5 w-3.5" />
                            Encerrada
                          </span>
                        )}
                      </td>
                      <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                        {vaga.candidatos}
                      </td>
                      <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{vaga.dataCriacao}</td>
                      <td className="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                        <div className="flex items-center justify-end gap-2">
                          <button onClick={() => handleViewDetails(vaga)} className="text-gray-400 hover:text-primary-600" title="Ver Detalhes">
                            <Eye className="h-4 w-4" />
                          </button>
                          {canPerformAction('edit', 'vagas') && (
                            <>
                              <button onClick={() => handleToggleDestaque(vaga)} className={`text-gray-400 ${vaga.destaque ? 'hover:text-yellow-500' : 'hover:text-gray-600'}`} title={vaga.destaque ? 'Remover Destaque' : 'Destacar Vaga'}>
                                <Star className={`h-4 w-4 ${vaga.destaque ? 'fill-current text-yellow-400' : ''}`} />
                              </button>
                              {vaga.status === 'aberta' && (
                                <button onClick={() => handleToggleStatus(vaga, 'pausada')} className="text-gray-400 hover:text-yellow-600" title="Pausar Vaga">
                                  <Pause className="h-4 w-4" />
                                </button>
                              )}
                              {vaga.status === 'pausada' && (
                                <button onClick={() => handleToggleStatus(vaga, 'aberta')} className="text-gray-400 hover:text-green-600" title="Reabrir Vaga">
                                  <Play className="h-4 w-4" />
                                </button>
                              )}
                              {vaga.status !== 'encerrada' && (
                                <button onClick={() => handleToggleStatus(vaga, 'encerrada')} className="text-gray-400 hover:text-red-600" title="Encerrar Vaga">
                                  <XCircle className="h-4 w-4" />
                                </button>
                              )}
                            </>
                          )}
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <Pagination
              currentPage={currentPage}
              totalPages={totalPages}
              totalItems={filteredVagas.length}
              itemsPerPage={itemsPerPage}
              onPageChange={setCurrentPage}
            />
          </>
        )}
      </div>

      <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title="Detalhes da Vaga">
        {selectedVaga && (
          <div className="space-y-4">
            <div className="flex items-center gap-4 border-b border-gray-100 pb-4">
              <div className="h-16 w-16 rounded-md bg-blue-50 flex items-center justify-center border border-blue-100">
                <Briefcase className="h-8 w-8 text-blue-600" />
              </div>
              <div>
                <h3 className="text-lg font-medium text-gray-900 flex items-center gap-2">
                  {selectedVaga.titulo}
                  {selectedVaga.destaque && <span className="inline-flex items-center rounded-full bg-yellow-50 px-2 py-1 text-xs font-medium text-yellow-800 ring-1 ring-inset ring-yellow-600/20">Destacada</span>}
                </h3>
                <p className="text-sm text-gray-500 flex items-center gap-1 mt-1">
                  <Building2 className="h-4 w-4" /> {selectedVaga.empresa}
                </p>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-sm font-medium text-gray-500">Status</p>
                <p className="mt-1 text-sm text-gray-900 capitalize">{selectedVaga.status}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-500">Local</p>
                <p className="mt-1 text-sm text-gray-900">{selectedVaga.local}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-500">Tipo de Contratação</p>
                <p className="mt-1 text-sm text-gray-900">{selectedVaga.tipo}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-500">Candidatos</p>
                <p className="mt-1 text-sm text-gray-900">{selectedVaga.candidatos}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-500">Data de Criação</p>
                <p className="mt-1 text-sm text-gray-900">{selectedVaga.dataCriacao}</p>
              </div>
            </div>
            <div className="mt-6 flex justify-end gap-3">
              <button onClick={() => setIsModalOpen(false)} className="rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
                Fechar
              </button>
              {canPerformAction('edit', 'vagas') && (
                <button className="rounded-md bg-primary-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-primary-500">
                  Editar Vaga
                </button>
              )}
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}

// app/pages/admin/vagas.vue
<script setup lang="ts">
import { 
  Search, 
  Filter, 
  Briefcase, 
  MapPin, 
  Building2, 
  Clock, 
  CheckCircle2, 
  XCircle, 
  MoreVertical, 
  Eye, 
  Play, 
  Pause, 
  Star 
} from 'lucide-vue-next'
import { useAdminPermissions } from '~/composables/useAdminPermissions'
import { useAdminAudit } from '~/composables/useAdminAudit'

definePageMeta({
  layout: 'admin-master',
  middleware: 'admin'
})

const { canPerformAction } = useAdminPermissions()
const { logAction } = useAdminAudit()

// UI State
const searchTerm = ref('')
const currentPage = ref(1)
const isLoading = ref(true)
const selectedVaga = ref<any>(null)
const isModalOpen = ref(false)
const itemsPerPage = 8

// Mock Data
const mockVagas = ref(Array.from({ length: 30 }, (_, i) => ({
  id: i + 1,
  titulo: `Vaga de Teste ${i + 1}`,
  empresa: `Empresa ${Math.floor(i / 3) + 1} Ltda`,
  local: i % 3 === 0 ? 'Remoto' : i % 2 === 0 ? 'São Paulo, SP' : 'Híbrido',
  status: i % 5 === 0 ? 'encerrada' : i % 4 === 0 ? 'pausada' : 'aberta',
  tipo: i % 3 === 0 ? 'PJ' : 'CLT',
  candidatos: Math.floor(Math.random() * 150),
  dataCriacao: `1${i % 9}/04/2026`,
  destaque: i % 7 === 0
})))

// Simulate loading
onMounted(() => {
  setTimeout(() => {
    isLoading.value = false
  }, 500)
})

// Filter logic
const filteredVagas = computed(() => {
  return mockVagas.value.filter(v => 
    v.titulo.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
    v.empresa.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
    v.local.toLowerCase().includes(searchTerm.value.toLowerCase())
  )
})

// Pagination logic
const totalPages = computed(() => Math.ceil(filteredVagas.value.length / itemsPerPage))
const paginatedVagas = computed(() => {
  const start = (currentPage.value - 1) * itemsPerPage
  return filteredVagas.value.slice(start, start + itemsPerPage)
})

watch(searchTerm, () => {
  currentPage.value = 1
})

const handleViewDetails = (vaga: any) => {
  selectedVaga.value = vaga
  isModalOpen.value = true
  logAction('view_vaga_details', 'vagas', { vagaId: vaga.id })
}

const handleToggleStatus = (vaga: any, newStatus: any) => {
  if (!canPerformAction('edit', 'vagas')) {
    alert('Permissão negada.')
    return
  }
  
  const index = mockVagas.value.findIndex(v => v.id === vaga.id)
  if (index !== -1) {
    mockVagas.value[index].status = newStatus
  }
  
  logAction('change_vaga_status', 'vagas', { vagaId: vaga.id, newStatus })
  alert(`Status da vaga "${vaga.titulo}" alterado para ${newStatus}.`)
}

const handleToggleDestaque = (vaga: any) => {
  if (!canPerformAction('edit', 'vagas')) return
  
  const index = mockVagas.value.findIndex(v => v.id === vaga.id)
  if (index !== -1) {
    mockVagas.value[index].destaque = !mockVagas.value[index].destaque
  }
  
  logAction('toggle_vaga_destaque', 'vagas', { vagaId: vaga.id, destaque: !vaga.destaque })
}
</script>

<template>
  <div class="space-y-8 animate-in fade-in duration-700">
    <!-- Header -->
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
      <div>
        <h1 class="text-3xl font-black text-slate-900 tracking-tight">Gestão de Vagas</h1>
        <p class="text-slate-500 font-medium mt-1">Modere as oportunidades publicadas no PebasPro.</p>
      </div>
      <div v-if="canPerformAction('create', 'vagas')">
        <button class="rounded-2xl bg-slate-900 px-6 py-3 text-sm font-black text-white shadow-xl shadow-slate-900/20 hover:bg-slate-800 transition-all flex items-center gap-2">
          Publicar Vaga Institucional
        </button>
      </div>
    </div>

    <!-- Stats -->
    <div class="grid grid-cols-2 gap-6 sm:grid-cols-4">
       <div v-for="stat in [
         { label: 'Total Registrado', value: '3.456', color: 'text-slate-900' },
         { label: 'Oportunidades Ativas', value: '1.245', color: 'text-green-600' },
         { label: 'Destaques Premium', value: '342', color: 'text-purple-600' },
         { label: 'Candidaturas Mês', value: '18.492', color: 'text-blue-600' }
       ]" :key="stat.label" class="p-6 bg-white rounded-[28px] border border-slate-100 shadow-sm transition-all hover:shadow-md">
          <p class="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">{{ stat.label }}</p>
          <h3 class="text-2xl font-black" :class="stat.color">{{ stat.value }}</h3>
       </div>
    </div>

    <!-- Filters -->
    <div class="flex flex-col md:flex-row gap-4 items-center justify-between bg-white p-6 rounded-[32px] shadow-sm border border-slate-100">
      <div class="relative w-full max-w-md">
        <Search class="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
        <input
          v-model="searchTerm"
          type="text"
          class="block w-full rounded-2xl border-slate-100 bg-slate-50/50 pl-11 pr-4 py-3 text-sm font-bold text-slate-900 placeholder:text-slate-400 focus:ring-green-500 focus:border-green-500 transition-all"
          placeholder="Filtrar por título, empresa ou local..."
        />
      </div>
      <button class="flex items-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-black text-slate-700 shadow-sm border border-slate-100 hover:bg-slate-50 transition-all">
        <Filter class="h-4 w-4" />
        Filtros Avançados
      </button>
    </div>

    <!-- Table -->
    <div class="bg-white rounded-[32px] shadow-sm border border-slate-100 overflow-hidden">
      <div v-if="isLoading" class="p-20 text-center">
        <div class="animate-spin h-10 w-10 border-4 border-green-500 border-t-transparent rounded-full mx-auto mb-4"></div>
        <p class="text-slate-400 font-black uppercase tracking-widest text-xs">Acessando Banco de Vagas...</p>
      </div>

      <AdminEmptyState 
        v-else-if="filteredVagas.length === 0"
        title="Nenhuma vaga localizada" 
        :description="`Não encontramos resultados ativos para '${searchTerm}'`"
      />

      <div v-else>
        <div class="overflow-x-auto">
          <table class="min-w-full divide-y divide-slate-50">
            <thead class="bg-slate-50/50">
              <tr>
                <th class="py-5 px-8 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Oportunidade</th>
                <th class="px-6 py-5 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Empresa</th>
                <th class="px-6 py-5 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Status</th>
                <th class="px-6 py-5 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Inscritos</th>
                <th class="px-6 py-5 text-right text-[10px] font-black text-slate-400 uppercase tracking-widest">Gerenciar</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-slate-50">
              <tr v-for="vaga in paginatedVagas" :key="vaga.id" class="group hover:bg-slate-50/50 transition-colors">
                <td class="whitespace-nowrap py-5 px-8">
                  <div class="flex items-center">
                    <div class="h-10 w-10 rounded-xl bg-blue-50 flex items-center justify-center text-blue-600 group-hover:bg-blue-600 group-hover:text-white transition-all">
                      <Briefcase class="h-5 w-5" />
                    </div>
                    <div class="ml-4">
                      <div class="text-sm font-black text-slate-900 flex items-center gap-2">
                        {{ vaga.titulo }}
                        <Star v-if="vaga.destaque" class="h-3 w-3 text-amber-400 fill-current" />
                      </div>
                      <div class="text-[10px] font-bold text-slate-400 uppercase flex items-center gap-2 mt-0.5">
                        <span class="flex items-center gap-1"><MapPin class="h-3 w-3" /> {{ vaga.local }}</span>
                        <span>&bull;</span>
                        <span>{{ vaga.tipo }}</span>
                      </div>
                    </div>
                  </div>
                </td>
                <td class="whitespace-nowrap px-6 py-5 text-xs font-bold text-slate-600">
                  <div class="flex items-center gap-2">
                     <Building2 class="h-4 w-4 text-slate-300" />
                     {{ vaga.empresa }}
                  </div>
                </td>
                <td class="whitespace-nowrap px-6 py-5">
                  <span v-if="vaga.status === 'aberta'" class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[9px] font-black uppercase tracking-wider bg-green-50 text-green-600 ring-1 ring-inset ring-green-600/20">
                    <CheckCircle2 class="h-3.5 w-3.5" /> Ativa
                  </span>
                  <span v-else-if="vaga.status === 'pausada'" class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[9px] font-black uppercase tracking-wider bg-amber-50 text-amber-600 ring-1 ring-inset ring-amber-600/20">
                    <Clock class="h-3.5 w-3.5" /> Pausada
                  </span>
                  <span v-else class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[9px] font-black uppercase tracking-wider bg-slate-50 text-slate-400 ring-1 ring-inset ring-slate-200">
                    <XCircle class="h-3.5 w-3.5" /> Encerrada
                  </span>
                </td>
                <td class="whitespace-nowrap px-6 py-5 text-xs font-black text-slate-900">
                  {{ vaga.candidatos }}
                </td>
                <td class="whitespace-nowrap px-8 py-5 text-right">
                  <div class="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button @click="handleViewDetails(vaga)" class="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-xl transition-all">
                      <Eye class="h-4 w-4" />
                    </button>
                    <template v-if="canPerformAction('edit', 'vagas')">
                      <button @click="handleToggleDestaque(vaga)" class="p-2 text-slate-400 hover:text-amber-500 hover:bg-amber-50 rounded-xl transition-all" :title="vaga.destaque ? 'Remover Destaque' : 'Destacar'">
                        <Star class="h-4 w-4" :class="{ 'fill-current text-amber-400': vaga.destaque }" />
                      </button>
                      <button v-if="vaga.status === 'aberta'" @click="handleToggleStatus(vaga, 'pausada')" class="p-2 text-slate-400 hover:text-amber-600 hover:bg-amber-50 rounded-xl transition-all">
                        <Pause class="h-4 w-4" />
                      </button>
                      <button v-if="vaga.status === 'pausada'" @click="handleToggleStatus(vaga, 'aberta')" class="p-2 text-slate-400 hover:text-green-600 hover:bg-green-50 rounded-xl transition-all">
                        <Play class="h-4 w-4" />
                      </button>
                    </template>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <AdminPagination 
          :current-page="currentPage" 
          :total-pages="totalPages" 
          :total-items="filteredVagas.length" 
          :items-per-page="itemsPerPage" 
          @page-change="currentPage = $event"
        />
      </div>
    </div>

    <!-- Details Modal -->
    <AdminModal :is-open="isModalOpen" @close="isModalOpen = false" title="Detalhamento da Oportunidade">
      <div v-if="selectedVaga" class="space-y-8">
        <div class="flex items-center gap-6 p-6 bg-slate-50 rounded-[28px]">
          <div class="h-20 w-20 rounded-[24px] bg-blue-600 flex items-center justify-center text-white shadow-xl shadow-blue-600/20">
            <Briefcase class="h-10 w-10" />
          </div>
          <div>
            <h3 class="text-2xl font-black text-slate-900 tracking-tight">{{ selectedVaga.titulo }}</h3>
            <p class="text-slate-500 font-bold uppercase tracking-widest text-[10px]">{{ selectedVaga.empresa }}</p>
          </div>
        </div>
        
        <div class="grid grid-cols-2 gap-8 px-2">
          <div v-for="info in [
            { label: 'Status Estratégico', value: selectedVaga.status, caps: true },
            { label: 'Local de Atuação', value: selectedVaga.local, caps: false },
            { label: 'Modelo de Contrato', value: selectedVaga.tipo, caps: false },
            { label: 'Volume de Candidatos', value: selectedVaga.candidatos, caps: false },
            { label: 'Data de Publicação', value: selectedVaga.dataCriacao, caps: false }
          ]" :key="info.label">
            <p class="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">{{ info.label }}</p>
            <p class="text-sm font-black text-slate-900" :class="{ 'uppercase text-green-600': info.caps && info.value === 'aberta' }">
              {{ info.value }}
            </p>
          </div>
        </div>

        <div class="pt-6 border-t border-slate-50 flex justify-end gap-3">
          <button @click="isModalOpen = false" class="rounded-2xl bg-slate-100 px-6 py-3 text-sm font-black text-slate-600 hover:bg-slate-200 transition-all">
            Fechar
          </button>
          <button v-if="canPerformAction('edit', 'vagas')" class="rounded-2xl bg-slate-900 px-6 py-3 text-sm font-black text-white shadow-xl shadow-slate-900/20 hover:bg-slate-800 transition-all">
             Editar Oportunidade
          </button>
        </div>
      </div>
    </AdminModal>
  </div>
</template>
