// app/pages/painel/empresa/compliance.vue
<script setup lang="ts">
import { Download, AlertTriangle } from 'lucide-vue-next'

definePageMeta({
  layout: 'empresa-master'
})
</script>

<template>
  <div class="space-y-8 animate-in fade-in duration-700">

    <!-- Header -->
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-6">
      <div>
        <h2 class="text-3xl font-black text-slate-900 tracking-tight">Compliance SST / eSocial</h2>
        <p class="text-slate-500 font-medium mt-1 uppercase text-[10px] tracking-[0.2em]">
          Central de riscos, exames ocupacionais e conformidade legal PEBASPRO.
        </p>
      </div>
      <div class="flex items-center gap-3">
        <button class="flex items-center gap-2 px-6 py-3 bg-white border border-slate-200 text-slate-600 rounded-2xl font-bold text-xs uppercase tracking-widest hover:bg-slate-50 transition-all shadow-sm">
          <Download :size="16" /> Exportar LNT
        </button>
        <button class="flex items-center gap-2 px-8 py-3 bg-green-600 text-white rounded-2xl font-black text-xs uppercase tracking-widest hover:bg-green-700 transition-all shadow-lg shadow-green-900/20">
          <AlertTriangle :size="16" /> Novo Alerta
        </button>
      </div>
    </div>

    <!-- Grid Principal -->
    <div class="grid grid-cols-1 lg:grid-cols-12 gap-8">

      <!-- Coluna Principal -->
      <div class="lg:col-span-8 flex flex-col gap-6">

        <!-- Visão Geral de Regulamentação -->
        <div class="bg-white rounded-[24px] border border-slate-100 shadow-sm p-6">
          <h3 class="text-lg font-black text-green-900 mb-5">Visão Geral de Regulamentação</h3>
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-5">
            <!-- ASOs Pendentes -->
            <div class="p-5 bg-slate-50 rounded-2xl border border-slate-100">
              <span class="text-[10px] font-black text-slate-400 uppercase tracking-widest">ASOs Pendentes</span>
              <div class="text-4xl font-black text-red-500 mt-1">14</div>
              <p class="text-xs text-slate-400 font-medium mt-2">Necessário agendamento imediato</p>
            </div>
            <!-- CIPA / Brigada -->
            <div class="p-5 bg-slate-50 rounded-2xl border border-slate-100">
              <span class="text-[10px] font-black text-slate-400 uppercase tracking-widest">CIPA / Brigada</span>
              <div class="text-4xl font-black text-[#1FAE66] mt-1">100%</div>
              <p class="text-xs text-slate-400 font-medium mt-2">Certificações em dia</p>
            </div>
          </div>
        </div>

        <!-- Histórico de Inspeções -->
        <div class="bg-white rounded-[24px] border border-slate-100 shadow-sm p-6">
          <h3 class="text-lg font-black text-green-900 mb-4">Histórico de Inspeções</h3>
          <p class="text-sm text-slate-400 font-medium">Nenhuma inspeção recente registrada no sistema.</p>
        </div>
      </div>

      <!-- Sidebar -->
      <div class="lg:col-span-4">
        <EmpresaCompliancePanel />
      </div>
    </div>

  </div>
</template>

<style scoped>
.animate-in {
  animation: fadeIn 0.7s cubic-bezier(0.2, 0.8, 0.2, 1);
}
@keyframes fadeIn {
  from { opacity: 0; transform: translateY(20px); }
  to   { opacity: 1; transform: translateY(0); }
}
</style>

// Nova pasta/src/views/Compliance.jsx
import React from 'react';
import { motion } from 'framer-motion';
import CompliancePanel from '../components/CompliancePanel';
import { ShieldCheck, Download, AlertTriangle } from 'lucide-react';
import './Views.css';

const Compliance = () => {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="view-container"
    >
      <div className="view-header">
        <div className="title-group">
          <h2>Compliance SST / eSocial</h2>
          <p>Central de riscos, exames ocupacionais e conformidade legal PEBASPRO.</p>
        </div>
        <div className="view-actions" style={{ display: 'flex', gap: '12px' }}>
          <button className="btn-secondary">
            <Download size={18} />
            Exportar LNT
          </button>
          <button className="btn-primary">
            <AlertTriangle size={18} />
            Novo Alerta
          </button>
        </div>
      </div>

      <div className="compliance-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 350px', gap: '24px' }}>
        <div className="compliance-main">
          <div className="pb-table-container" style={{ padding: '24px', marginBottom: '24px' }}>
            <h3 style={{ fontSize: '18px', color: 'var(--pb-blue-deep)', fontWeight: '800', marginBottom: '16px' }}>Visão Geral de Regulamentação</h3>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '20px' }}>
              <div style={{ padding: '20px', background: '#F8FAFC', borderRadius: '12px', border: '1px solid var(--pb-gray-light)' }}>
                <span style={{ fontSize: '12px', color: 'var(--pb-text-secondary)', fontWeight: '700', textTransform: 'uppercase' }}>ASOs Pendentes</span>
                <div style={{ fontSize: '24px', fontWeight: '900', color: '#FF5252', marginTop: '4px' }}>14</div>
                <p style={{ fontSize: '12px', color: 'var(--pb-text-secondary)', marginTop: '8px' }}>Necessário agendamento imediato</p>
              </div>
              <div style={{ padding: '20px', background: '#F8FAFC', borderRadius: '12px', border: '1px solid var(--pb-gray-light)' }}>
                <span style={{ fontSize: '12px', color: 'var(--pb-text-secondary)', fontWeight: '700', textTransform: 'uppercase' }}>CIPA / Brigada</span>
                <div style={{ fontSize: '24px', fontWeight: '900', color: 'var(--pb-green-main)', marginTop: '4px' }}>100%</div>
                <p style={{ fontSize: '12px', color: 'var(--pb-text-secondary)', marginTop: '8px' }}>Certificações em dia</p>
              </div>
            </div>
          </div>
          
          <div className="pb-table-container" style={{ padding: '24px' }}>
             <h3 style={{ fontSize: '18px', color: 'var(--pb-blue-deep)', fontWeight: '800', marginBottom: '16px' }}>Histórico de Inspeções</h3>
             <p style={{ color: 'var(--pb-text-secondary)', fontSize: '14px' }}>Nenhuma inspeção recente registrada no sistema.</p>
          </div>
        </div>

        <div className="compliance-sidebar">
          <CompliancePanel />
        </div>
      </div>
    </motion.div>
  );
};

export default Compliance;
