// app/pages/admin/usuarios/empresas.vue
<script setup lang="ts">
import { 
  Search, 
  Filter, 
  Building2, 
  Briefcase, 
  Eye, 
  Lock, 
  Unlock, 
  Edit, 
  ShieldCheck 
} from 'lucide-vue-next'
import { useAdminPermissions } from '~/composables/useAdminPermissions'
import { useAdminAudit } from '~/composables/useAdminAudit'

definePageMeta({
  layout: 'admin-master',
  middleware: 'admin'
})

const { canPerformAction } = useAdminPermissions()
const { logAction } = useAdminAudit()

// UI State
const searchTerm = ref('')
const currentPage = ref(1)
const isLoading = ref(true)
const selectedEmpresa = ref<any>(null)
const isModalOpen = ref(false)
const itemsPerPage = 10

// Mock Data
const mockEmpresas = ref(Array.from({ length: 25 }, (_, i) => ({
  id: i + 1,
  nome: `Empresa ${i + 1} Ltda`,
  cnpj: `${(10 + i).toString().padStart(2, '0')}.345.678/0001-90`,
  email: `contato@empresa${i + 1}.com.br`,
  status: i % 5 === 0 ? 'bloqueado' : i % 3 === 0 ? 'pendente' : 'ativo',
  vagasAtivas: Math.floor(Math.random() * 15),
  plano: i % 4 === 0 ? 'Premium' : i % 2 === 0 ? 'Pro' : 'Gratuito',
  dataCadastro: `1${i % 9}/01/2026`,
})))

// Simulate loading
onMounted(() => {
  setTimeout(() => {
    isLoading.value = false
  }, 500)
})

// Filter logic
const filteredEmpresas = computed(() => {
  return mockEmpresas.value.filter(e => 
    e.nome.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
    e.cnpj.includes(searchTerm.value) ||
    e.email.toLowerCase().includes(searchTerm.value.toLowerCase())
  )
})

// Pagination logic
const totalPages = computed(() => Math.ceil(filteredEmpresas.value.length / itemsPerPage))
const paginatedEmpresas = computed(() => {
  const start = (currentPage.value - 1) * itemsPerPage
  return filteredEmpresas.value.slice(start, start + itemsPerPage)
})

// Watch search to reset page
watch(searchTerm, () => {
  currentPage.value = 1
})

const handleViewDetails = (empresa: any) => {
  selectedEmpresa.value = empresa
  isModalOpen.value = true
  logAction('view_empresa_details', 'empresas', { empresaId: empresa.id })
}

const handleToggleStatus = (empresa: any) => {
  if (!canPerformAction('edit', 'empresas')) {
    alert('Você não tem permissão para realizar esta ação.')
    return
  }
  const newStatus = empresa.status === 'bloqueado' ? 'ativo' : 'bloqueado'
  
  const index = mockEmpresas.value.findIndex(e => e.id === empresa.id)
  if (index !== -1) {
    mockEmpresas.value[index].status = newStatus
  }
  
  logAction('toggle_empresa_status', 'empresas', { empresaId: empresa.id, newStatus })
  alert(`Status da empresa ${empresa.nome} alterado para ${newStatus}. (Simulação)`)
}

const handleValidate = (empresa: any) => {
  if (!canPerformAction('edit', 'empresas')) return
  
  const index = mockEmpresas.value.findIndex(e => e.id === empresa.id)
  if (index !== -1) {
    mockEmpresas.value[index].status = 'ativo'
  }
  
  logAction('validate_empresa', 'empresas', { empresaId: empresa.id })
  alert(`Cadastro da empresa ${empresa.nome} validado com sucesso. (Simulação)`)
}
</script>

<template>
  <div class="space-y-8 animate-in fade-in duration-700">
    <!-- Header -->
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
      <div>
        <h1 class="text-3xl font-black text-slate-900 tracking-tight">Gestão de Empresas</h1>
        <p class="text-slate-500 font-medium mt-1">Gerencie cadastros, planos e acessos das contratantes.</p>
      </div>
      <div v-if="canPerformAction('create', 'empresas')">
        <button class="rounded-2xl bg-slate-900 px-6 py-3 text-sm font-black text-white shadow-xl shadow-slate-900/20 hover:bg-slate-800 transition-all flex items-center gap-2">
          Adicionar Nova Empresa
        </button>
      </div>
    </div>

    <!-- Filters -->
    <div class="flex flex-col md:flex-row gap-4 items-center justify-between bg-white p-6 rounded-[32px] shadow-sm border border-slate-100">
      <div class="relative w-full max-w-md">
        <Search class="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
        <input
          v-model="searchTerm"
          type="text"
          class="block w-full rounded-2xl border-slate-100 bg-slate-50/50 pl-11 pr-4 py-3 text-sm font-bold text-slate-900 placeholder:text-slate-400 focus:ring-green-500 focus:border-green-500 transition-all"
          placeholder="Buscar por nome, CNPJ ou email..."
        />
      </div>
      <button class="flex items-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-black text-slate-700 shadow-sm border border-slate-100 hover:bg-slate-50 transition-all">
        <Filter class="h-4 w-4" />
        Filtros Avançados
      </button>
    </div>

    <!-- Table -->
    <div class="bg-white rounded-[32px] shadow-sm border border-slate-100 overflow-hidden">
      <div v-if="isLoading" class="p-20 text-center">
        <div class="animate-spin h-10 w-10 border-4 border-green-500 border-t-transparent rounded-full mx-auto mb-4"></div>
        <p class="text-slate-400 font-black uppercase tracking-widest text-xs">Carregando Empresas...</p>
      </div>

      <AdminEmptyState 
        v-else-if="filteredEmpresas.length === 0"
        title="Nenhuma empresa encontrada" 
        :description="`Não encontramos resultados para sua busca: '${searchTerm}'`"
      />

      <div v-else>
        <div class="overflow-x-auto">
          <table class="min-w-full divide-y divide-slate-50">
            <thead class="bg-slate-50/50">
              <tr>
                <th class="py-5 px-8 text-left text-xs font-black text-slate-400 uppercase tracking-widest">Empresa</th>
                <th class="px-6 py-5 text-left text-xs font-black text-slate-400 uppercase tracking-widest">Status</th>
                <th class="px-6 py-5 text-left text-xs font-black text-slate-400 uppercase tracking-widest">Plano</th>
                <th class="px-6 py-5 text-left text-xs font-black text-slate-400 uppercase tracking-widest">Vagas Ativas</th>
                <th class="px-6 py-5 text-right text-xs font-black text-slate-400 uppercase tracking-widest">Ações</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-slate-50">
              <tr v-for="empresa in paginatedEmpresas" :key="empresa.id" class="group hover:bg-slate-50/50 transition-colors">
                <td class="whitespace-nowrap py-5 px-8">
                  <div class="flex items-center">
                    <div class="h-10 w-10 rounded-xl bg-blue-50 flex items-center justify-center text-blue-600 group-hover:bg-blue-600 group-hover:text-white transition-all">
                      <Building2 class="h-5 w-5" />
                    </div>
                    <div class="ml-4">
                      <div class="text-sm font-black text-slate-900">{{ empresa.nome }}</div>
                      <div class="text-xs font-medium text-slate-400">{{ empresa.cnpj }}</div>
                    </div>
                  </div>
                </td>
                <td class="whitespace-nowrap px-6 py-5">
                  <span v-if="empresa.status === 'ativo'" class="inline-flex items-center px-2.5 py-1 rounded-full text-[10px] font-black uppercase tracking-wider bg-green-50 text-green-600 ring-1 ring-inset ring-green-600/20">
                    Ativo
                  </span>
                  <span v-else-if="empresa.status === 'pendente'" class="inline-flex items-center px-2.5 py-1 rounded-full text-[10px] font-black uppercase tracking-wider bg-amber-50 text-amber-600 ring-1 ring-inset ring-amber-600/20">
                    Aguardando Validação
                  </span>
                  <span v-else class="inline-flex items-center px-2.5 py-1 rounded-full text-[10px] font-black uppercase tracking-wider bg-red-50 text-red-600 ring-1 ring-inset ring-red-600/10">
                    Bloqueado
                  </span>
                </td>
                <td class="whitespace-nowrap px-6 py-5 text-sm font-bold text-slate-600">
                  <span class="inline-flex items-center rounded-lg bg-slate-50 px-2 py-1 text-[9px] font-black uppercase tracking-tight text-slate-500 ring-1 ring-inset ring-slate-200">
                    {{ empresa.plano }}
                  </span>
                </td>
                <td class="whitespace-nowrap px-6 py-5">
                   <div class="flex items-center gap-1.5 text-xs font-black text-slate-700">
                      <Briefcase class="h-4 w-4 text-slate-400" />
                      {{ empresa.vagasAtivas }}
                   </div>
                </td>
                <td class="whitespace-nowrap px-8 py-5 text-right">
                  <div class="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button @click="handleViewDetails(empresa)" class="p-2 text-slate-400 hover:text-green-600 hover:bg-green-50 rounded-xl transition-all">
                      <Eye class="h-4 w-4" />
                    </button>
                    <template v-if="canPerformAction('edit', 'empresas')">
                      <button v-if="empresa.status === 'pendente'" @click="handleValidate(empresa)" class="p-2 text-slate-400 hover:text-green-600 hover:bg-green-50 rounded-xl transition-all" title="Validar Cadastro">
                        <ShieldCheck class="h-4 w-4" />
                      </button>
                      <button class="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-xl transition-all">
                        <Edit class="h-4 w-4" />
                      </button>
                      <button 
                        @click="handleToggleStatus(empresa)" 
                        :class="[empresa.status === 'bloqueado' ? 'hover:text-green-600 hover:bg-green-50' : 'hover:text-red-600 hover:bg-red-50', 'p-2 text-slate-400 rounded-xl transition-all']"
                      >
                        <Unlock v-if="empresa.status === 'bloqueado'" class="h-4 w-4" />
                        <Lock v-else class="h-4 w-4" />
                      </button>
                    </template>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <AdminPagination 
          :current-page="currentPage" 
          :total-pages="totalPages" 
          :total-items="filteredEmpresas.length" 
          :items-per-page="itemsPerPage" 
          @page-change="currentPage = $event"
        />
      </div>
    </div>

    <!-- Details Modal -->
    <AdminModal :is-open="isModalOpen" @close="isModalOpen = false" title="Ficha Cadastral">
      <div v-if="selectedEmpresa" class="space-y-8">
        <div class="flex items-center gap-6 p-6 bg-slate-50 rounded-[28px]">
          <div class="h-20 w-20 rounded-[24px] bg-blue-100 flex items-center justify-center text-blue-600 shadow-lg shadow-blue-100/20">
            <Building2 class="h-10 w-10" />
          </div>
          <div>
            <h3 class="text-2xl font-black text-slate-900 tracking-tight">{{ selectedEmpresa.nome }}</h3>
            <p class="text-slate-500 font-bold uppercase tracking-widest text-[10px]">{{ selectedEmpresa.cnpj }}</p>
          </div>
        </div>
        
        <div class="grid grid-cols-2 gap-6 px-2">
          <div v-for="info in [
            { label: 'Contato Oficial', value: selectedEmpresa.email, caps: false },
            { label: 'Status do Registro', value: selectedEmpresa.status, caps: true },
            { label: 'Plano Ativo', value: selectedEmpresa.plano, caps: false },
            { label: 'Vagas Publicadas', value: selectedEmpresa.vagasAtivas, caps: false },
            { label: 'Data de Fundação/Cadastro', value: selectedEmpresa.dataCadastro, caps: false }
          ]" :key="info.label" :class="{ 'col-span-2 border-b border-slate-50 pb-4': info.label === 'Contato Oficial' }">
            <p class="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">{{ info.label }}</p>
            <p class="text-sm font-black text-slate-900" :class="{ 'uppercase text-green-600': info.caps && info.value === 'ativo' }">
              {{ info.value }}
            </p>
          </div>
        </div>

        <div class="pt-6 border-t border-slate-50 flex justify-end gap-3">
          <button @click="isModalOpen = false" class="rounded-2xl bg-slate-100 px-6 py-3 text-sm font-black text-slate-600 hover:bg-slate-200 transition-all">
            Fechar
          </button>
          <button v-if="canPerformAction('edit', 'empresas')" class="rounded-2xl bg-slate-900 px-6 py-3 text-sm font-black text-white shadow-xl shadow-slate-900/20 hover:bg-slate-800 transition-all">
            Editar Cadastro
          </button>
        </div>
      </div>
    </AdminModal>
  </div>
</template>

// pebaspro-master-administrativo/src/pages/Empresas.tsx
import React, { useState, useEffect, useMemo } from 'react';
import { Search, Filter, Building2, MoreVertical, CheckCircle2, XCircle, FileText, Briefcase, Eye, Lock, Unlock, ShieldCheck } from 'lucide-react';
import { Modal } from '../components/ui/Modal';
import { Pagination } from '../components/ui/Pagination';
import { EmptyState } from '../components/ui/EmptyState';
import { usePermissions } from '../hooks/usePermissions';
import { useAudit } from '../hooks/useAudit';

const mockEmpresas = Array.from({ length: 25 }, (_, i) => ({
  id: i + 1,
  nome: `Empresa ${i + 1} Ltda`,
  cnpj: `${(10 + i).toString().padStart(2, '0')}.345.678/0001-90`,
  email: `contato@empresa${i + 1}.com.br`,
  status: i % 5 === 0 ? 'bloqueado' : i % 3 === 0 ? 'pendente' : 'ativo',
  vagasAtivas: Math.floor(Math.random() * 15),
  plano: i % 4 === 0 ? 'Premium' : i % 2 === 0 ? 'Pro' : 'Gratuito',
  dataCadastro: `1${i % 9}/01/2026`,
}));

export default function Empresas() {
  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [isLoading, setIsLoading] = useState(true);
  const [selectedEmpresa, setSelectedEmpresa] = useState<any>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const { canPerformAction } = usePermissions();
  const { logAction } = useAudit();
  const itemsPerPage = 10;

  useEffect(() => {
    const timer = setTimeout(() => setIsLoading(false), 500);
    return () => clearTimeout(timer);
  }, []);

  const filteredEmpresas = useMemo(() => {
    return mockEmpresas.filter(e =>
      e.nome.toLowerCase().includes(searchTerm.toLowerCase()) ||
      e.cnpj.includes(searchTerm) ||
      e.email.toLowerCase().includes(searchTerm.toLowerCase())
    );
  }, [searchTerm]);

  const totalPages = Math.ceil(filteredEmpresas.length / itemsPerPage);
  const paginatedEmpresas = filteredEmpresas.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  useEffect(() => {
    setCurrentPage(1);
  }, [searchTerm]);

  const handleViewDetails = (empresa: any) => {
    setSelectedEmpresa(empresa);
    setIsModalOpen(true);
    logAction('view_empresa_details', 'empresas', { empresaId: empresa.id });
  };

  const handleToggleStatus = (empresa: any) => {
    if (!canPerformAction('edit', 'empresas')) {
      alert('Você não tem permissão para realizar esta ação.');
      return;
    }
    const newStatus = empresa.status === 'bloqueado' ? 'ativo' : 'bloqueado';
    logAction('toggle_empresa_status', 'empresas', { empresaId: empresa.id, newStatus });
    alert(`Status da empresa ${empresa.nome} alterado para ${newStatus}. (Simulação)`);
  };

  const handleValidate = (empresa: any) => {
    if (!canPerformAction('edit', 'empresas')) return;
    logAction('validate_empresa', 'empresas', { empresaId: empresa.id });
    alert(`Cadastro da empresa ${empresa.nome} validado com sucesso. (Simulação)`);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-gray-900">Gestão de Empresas</h1>
          <p className="mt-1 text-sm text-gray-500">
            Gerencie cadastros, planos e acessos das empresas na plataforma.
          </p>
        </div>
        <div className="flex items-center gap-2">
          {canPerformAction('create', 'empresas') && (
            <button className="inline-flex items-center gap-2 rounded-md bg-primary-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-primary-500">
              Adicionar Empresa
            </button>
          )}
        </div>
      </div>

      {/* Filters and Search */}
      <div className="flex flex-col sm:flex-row gap-4 items-center justify-between bg-white p-4 rounded-xl shadow-sm border border-gray-100">
        <div className="relative w-full sm:max-w-md">
          <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
            <Search className="h-4 w-4 text-gray-400" />
          </div>
          <input
            type="text"
            className="block w-full rounded-md border-0 py-1.5 pl-10 pr-3 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-600 sm:text-sm sm:leading-6"
            placeholder="Buscar por nome, CNPJ ou email..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
        </div>
        <div className="flex gap-2 w-full sm:w-auto">
          <button className="inline-flex items-center gap-2 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
            <Filter className="h-4 w-4 text-gray-500" />
            Filtros Avançados
          </button>
        </div>
      </div>

      {/* Table */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        {isLoading ? (
          <div className="p-12 text-center text-gray-500">Carregando dados...</div>
        ) : filteredEmpresas.length === 0 ? (
          <EmptyState
            title="Nenhuma empresa encontrada"
            description={`Não encontramos resultados para "${searchTerm}".`}
          />
        ) : (
          <>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Empresa</th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Status</th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Plano</th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Vagas Ativas</th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Cadastro</th>
                    <th scope="col" className="relative py-3.5 pl-3 pr-4 sm:pr-6">
                      <span className="sr-only">Ações</span>
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200 bg-white">
                  {paginatedEmpresas.map((empresa) => (
                    <tr key={empresa.id} className="hover:bg-gray-50">
                      <td className="whitespace-nowrap py-4 pl-4 pr-3 sm:pl-6">
                        <div className="flex items-center">
                          <div className="h-10 w-10 flex-shrink-0 rounded-md bg-primary-50 flex items-center justify-center border border-primary-100">
                            <Building2 className="h-5 w-5 text-primary-600" />
                          </div>
                          <div className="ml-4">
                            <div className="font-medium text-gray-900">{empresa.nome}</div>
                            <div className="text-sm text-gray-500">{empresa.cnpj}</div>
                          </div>
                        </div>
                      </td>
                      <td className="whitespace-nowrap px-3 py-4 text-sm">
                        {empresa.status === 'ativo' && (
                          <span className="inline-flex items-center gap-1.5 rounded-full bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
                            Ativo
                          </span>
                        )}
                        {empresa.status === 'pendente' && (
                          <span className="inline-flex items-center gap-1.5 rounded-full bg-yellow-50 px-2 py-1 text-xs font-medium text-yellow-800 ring-1 ring-inset ring-yellow-600/20">
                            Aguardando Validação
                          </span>
                        )}
                        {empresa.status === 'bloqueado' && (
                          <span className="inline-flex items-center gap-1.5 rounded-full bg-red-50 px-2 py-1 text-xs font-medium text-red-700 ring-1 ring-inset ring-red-600/10">
                            Bloqueado
                          </span>
                        )}
                      </td>
                      <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                        <span className="inline-flex items-center rounded-md bg-gray-50 px-2 py-1 text-xs font-medium text-gray-600 ring-1 ring-inset ring-gray-500/10">
                          {empresa.plano}
                        </span>
                      </td>
                      <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                        <div className="flex items-center gap-1.5">
                          <Briefcase className="h-4 w-4 text-gray-400" />
                          {empresa.vagasAtivas}
                        </div>
                      </td>
                      <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{empresa.dataCadastro}</td>
                      <td className="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                        <div className="flex items-center justify-end gap-2">
                          <button onClick={() => handleViewDetails(empresa)} className="text-gray-400 hover:text-primary-600" title="Ver Detalhes">
                            <Eye className="h-4 w-4" />
                          </button>
                          {canPerformAction('edit', 'empresas') && (
                            <>
                              {empresa.status === 'pendente' && (
                                <button onClick={() => handleValidate(empresa)} className="text-gray-400 hover:text-green-600" title="Validar Cadastro">
                                  <ShieldCheck className="h-4 w-4" />
                                </button>
                              )}
                              <button onClick={() => handleToggleStatus(empresa)} className={`text-gray-400 ${empresa.status === 'bloqueado' ? 'hover:text-green-600' : 'hover:text-red-600'}`} title={empresa.status === 'bloqueado' ? 'Desbloquear' : 'Bloquear'}>
                                {empresa.status === 'bloqueado' ? <Unlock className="h-4 w-4" /> : <Lock className="h-4 w-4" />}
                              </button>
                            </>
                          )}
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <Pagination
              currentPage={currentPage}
              totalPages={totalPages}
              totalItems={filteredEmpresas.length}
              itemsPerPage={itemsPerPage}
              onPageChange={setCurrentPage}
            />
          </>
        )}
      </div>

      <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title="Detalhes da Empresa">
        {selectedEmpresa && (
          <div className="space-y-4">
            <div className="flex items-center gap-4 border-b border-gray-100 pb-4">
              <div className="h-16 w-16 rounded-md bg-primary-50 flex items-center justify-center border border-primary-100">
                <Building2 className="h-8 w-8 text-primary-600" />
              </div>
              <div>
                <h3 className="text-lg font-medium text-gray-900">{selectedEmpresa.nome}</h3>
                <p className="text-sm text-gray-500">{selectedEmpresa.cnpj}</p>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-sm font-medium text-gray-500">Email de Contato</p>
                <p className="mt-1 text-sm text-gray-900">{selectedEmpresa.email}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-500">Status</p>
                <p className="mt-1 text-sm text-gray-900 capitalize">{selectedEmpresa.status}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-500">Plano</p>
                <p className="mt-1 text-sm text-gray-900">{selectedEmpresa.plano}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-500">Vagas Ativas</p>
                <p className="mt-1 text-sm text-gray-900">{selectedEmpresa.vagasAtivas}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-500">Data de Cadastro</p>
                <p className="mt-1 text-sm text-gray-900">{selectedEmpresa.dataCadastro}</p>
              </div>
            </div>
            <div className="mt-6 flex justify-end gap-3">
              <button onClick={() => setIsModalOpen(false)} className="rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
                Fechar
              </button>
              {canPerformAction('edit', 'empresas') && (
                <button className="rounded-md bg-primary-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-primary-500">
                  Editar Empresa
                </button>
              )}
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}
