// app/pages/admin/moderacao.vue
<script setup lang="ts">
import {
  Search,
  Filter,
  ShieldAlert,
  AlertTriangle,
  Flag,
  UserX,
  MessageSquare,
  MoreVertical,
  Eye,
  Ban,
  Archive,
  RotateCcw,
  CheckCircle2,
  History
} from 'lucide-vue-next'
import { useAdminPermissions } from '~/composables/useAdminPermissions'
import { useAdminAudit } from '~/composables/useAdminAudit'

definePageMeta({
  layout: 'admin-master',
  middleware: 'admin'
})

const { canPerformAction } = useAdminPermissions()
const { logAction } = useAdminAudit()

// Tabs
type TabType = 'denuncias' | 'avaliacoes' | 'historico'
const tabs: { id: TabType, name: string, icon: any }[] = [
  { id: 'denuncias', name: 'Denúncias', icon: ShieldAlert },
  { id: 'avaliacoes', name: 'Avaliações Sinalizadas', icon: Flag },
  { id: 'historico', name: 'Histórico Disciplinar', icon: History },
]

// UI State
const activeTab = ref<TabType>('denuncias')
const searchTerm = ref('')
const currentPage = ref(1)
const isLoading = ref(true)
const selectedItem = ref<any>(null)
const isModalOpen = ref(false)
const itemsPerPage = 8

// Mock Data
const mockDenuncias = ref(Array.from({ length: 45 }, (_, i) => ({
  id: i + 1,
  tipo: i % 3 === 0 ? 'Comportamento Inadequado' : i % 2 === 0 ? 'Vaga Falsa' : 'Perfil Falso',
  reportado: `Usuário Reportado ${i}`,
  autor: `Autor ${i}`,
  status: i % 4 === 0 ? 'resolvido' : i % 3 === 0 ? 'pendente' : 'em_analise',
  prioridade: i % 5 === 0 ? 'alta' : i % 2 === 0 ? 'media' : 'baixa',
  data: `1${i % 9}/04/2026`,
  detalhes: 'Detalhes da denúncia simulados aqui para visualização no modal.'
})))

const mockAvaliacoes = ref(Array.from({ length: 25 }, (_, i) => ({
  id: i + 1,
  prestador: `Prestador ${i}`,
  cliente: `Cliente ${i}`,
  nota: (i % 5) + 1,
  comentario: i % 2 === 0 ? 'Comentário suspeito de spam ou ofensa.' : 'Avaliação muito baixa sem justificativa clara.',
  status: i % 3 === 0 ? 'em_analise' : 'sinalizada',
  data: `1${i % 9}/04/2026`
})))

onMounted(() => {
  setTimeout(() => isLoading.value = false, 500)
})

const currentData = computed(() => {
  if (activeTab.value === 'denuncias') {
    return mockDenuncias.value.filter(d => 
      d.reportado.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
      d.autor.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
      d.id.toString().includes(searchTerm.value)
    )
  }
  return mockAvaliacoes.value.filter(a => 
    a.prestador.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
    a.cliente.toLowerCase().includes(searchTerm.value.toLowerCase())
  )
})

const totalPages = computed(() => Math.ceil(currentData.value.length / itemsPerPage))
const paginatedData = computed(() => {
  const start = (currentPage.value - 1) * itemsPerPage
  return currentData.value.slice(start, start + itemsPerPage)
})

watch([activeTab, searchTerm], () => {
  currentPage.value = 1
})

const handleViewDetails = (item: any) => {
  selectedItem.value = { ...item, type: activeTab.value }
  isModalOpen.value = true
  logAction(`view_${activeTab.value}_details`, 'moderacao', { itemId: item.id })
}

const handleAction = (action: string, item?: any) => {
  if (!canPerformAction('edit', 'moderacao')) {
    alert('Permissão negada.')
    return
  }
  logAction(`${action}_moderacao`, 'moderacao', item ? { itemId: item.id } : undefined)
  alert(`Operação "${action}" executada com sucesso!`)
}

const stats = computed(() => ([
  { label: 'Denúncias Pendentes', value: mockDenuncias.value.filter(d => d.status === 'pendente').length, color: 'text-slate-900' },
  { label: 'Prioridade Máxima', value: mockDenuncias.value.filter(d => d.prioridade === 'alta').length, color: 'text-red-600' },
  { label: 'Review em Análise', value: mockAvaliacoes.value.filter(a => a.status === 'em_analise').length, color: 'text-amber-600' },
  { label: 'Suspensões Efetivas', value: '156', color: 'text-slate-500' }
]))
</script>

<template>
  <div class="space-y-8 animate-in fade-in duration-700">
    <!-- Header -->
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
      <div>
        <h1 class="text-3xl font-black text-slate-900 tracking-tight">Moderação & Confiança</h1>
        <p class="text-slate-500 font-medium mt-1">Garantindo a integridade e segurança do ecossistema PebasPro.</p>
      </div>
    </div>

    <!-- Mod Stats -->
    <div class="grid grid-cols-2 lg:grid-cols-4 gap-6">
       <div v-for="stat in stats" :key="stat.label" class="p-6 bg-white rounded-[28px] border border-slate-100 shadow-sm transition-all hover:shadow-md">
          <p class="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">{{ stat.label }}</p>
          <div class="flex items-end justify-between">
             <h3 class="text-3xl font-black" :class="stat.color">{{ stat.value }}</h3>
             <div class="h-8 w-8 rounded-lg bg-slate-50 flex items-center justify-center text-slate-300">
                <ShieldAlert v-if="stat.red" class="h-4 w-4" />
                <Flag v-else class="h-4 w-4" />
             </div>
          </div>
       </div>
    </div>

    <div class="space-y-6">
      <!-- Tabs Layout -->
      <div class="bg-white rounded-[32px] shadow-sm border border-slate-100 overflow-hidden">
        <div class="flex border-b border-slate-50 p-2 overflow-x-auto scrollbar-hide bg-slate-50/20">
          <button 
            v-for="tab in tabs" 
            :key="tab.id"
            @click="activeTab = tab.id"
            :class="[
              activeTab === tab.id ? 'bg-red-600 text-white shadow-lg' : 'text-slate-500 hover:bg-white',
              'flex items-center gap-2 px-6 py-3 rounded-2xl text-xs font-black transition-all whitespace-nowrap'
            ]"
          >
            <component :is="tab.icon" class="h-4 w-4" />
            {{ tab.name }}
          </button>
        </div>

        <!-- Search and Filters -->
        <div v-if="activeTab !== 'historico'" class="p-6 border-b border-slate-50 flex flex-wrap items-center justify-between gap-4">
           <div class="relative flex-1 min-w-[200px] max-w-sm">
              <Search class="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
              <input
                v-model="searchTerm"
                class="w-full bg-slate-50/50 border-none rounded-xl pl-11 pr-4 py-2 text-sm font-bold text-slate-900 placeholder:text-slate-400 focus:ring-2 focus:ring-red-500 transition-all"
                :placeholder="activeTab === 'denuncias' ? 'ID ou Usuário Reportado...' : 'Prestador ou Cliente...'"
              />
           </div>
           <div class="flex items-center gap-3">
              <select v-if="activeTab === 'denuncias'" class="bg-slate-50 border-none rounded-xl px-4 py-2 text-xs font-black text-slate-600 focus:ring-2 focus:ring-red-500 outline-none">
                 <option>Todas as Prioridades</option>
                 <option>Alta</option>
                 <option>Média</option>
                 <option>Baixa</option>
              </select>
              <button class="p-2.5 text-slate-400 hover:text-slate-900 hover:bg-slate-50 rounded-xl transition-all">
                 <Filter class="h-4 w-4" />
              </button>
           </div>
        </div>

        <!-- Content Area -->
        <div class="min-h-[400px]">
          <div v-if="isLoading" class="flex flex-col items-center justify-center p-20">
             <div class="h-10 w-10 border-4 border-slate-100 border-t-red-500 animate-spin rounded-full mb-4" />
             <p class="text-[10px] font-black text-slate-400 uppercase tracking-widest">Escaneando Relatos...</p>
          </div>

          <div v-else-if="activeTab === 'historico'" class="p-20 text-center">
             <div class="h-20 w-20 bg-slate-50 rounded-full flex items-center justify-center mx-auto mb-6 text-slate-300">
                <History class="h-10 w-10" />
             </div>
             <h4 class="text-xl font-black text-slate-900 mb-2 tracking-tight">Histórico de Moderação</h4>
             <p class="text-slate-500 font-medium max-w-sm mx-auto">Busque por um UUID de usuário para extrair o dossiê completo de advertências e infrações.</p>
             <div class="mt-8 max-w-xs mx-auto">
                <input class="w-full bg-slate-50 border border-slate-100 rounded-xl px-4 py-3 text-sm font-black text-center focus:ring-red-500" placeholder="UUID DO USUÁRIO" />
             </div>
          </div>
          
          <AdminEmptyState 
            v-else-if="currentData.length === 0"
            title="Área Limpa"
            :description="`Nenhum registro de '${activeTab}' pendente para '${searchTerm}'.`"
          />

          <div v-else class="overflow-x-auto">
            <table class="min-w-full divide-y divide-slate-50">
               <thead class="bg-slate-50/30">
                  <tr v-if="activeTab === 'denuncias'">
                    <th class="py-4 px-8 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Ocorrência</th>
                    <th class="px-6 py-4 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Reportado</th>
                    <th class="px-6 py-4 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Autor</th>
                    <th class="px-6 py-4 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Status</th>
                    <th class="px-6 py-4 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Severidade</th>
                    <th class="px-6 py-4 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Data</th>
                    <th class="px-6 py-4 text-right"></th>
                  </tr>
                  <tr v-else-if="activeTab === 'avaliacoes'">
                    <th class="py-4 px-8 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Feedback / Nota</th>
                    <th class="px-6 py-4 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Prestador</th>
                    <th class="px-6 py-4 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Cliente</th>
                    <th class="px-6 py-4 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Status</th>
                    <th class="px-6 py-4 text-right"></th>
                  </tr>
               </thead>
               <tbody class="divide-y divide-slate-50">
                  <tr v-for="item in paginatedData" :key="item.id" class="group hover:bg-slate-50/50 transition-colors">
                     <!-- DENUNCIAS ROW -->
                     <template v-if="activeTab === 'denuncias'">
                        <td class="py-5 px-8">
                           <div class="flex items-center gap-4">
                              <div :class="[
                                item.prioridade === 'alta' ? 'bg-red-50 text-red-600' : 'bg-amber-50 text-amber-600',
                                'h-10 w-10 rounded-xl flex items-center justify-center transition-all group-hover:scale-110 shadow-sm ring-1 ring-inset ring-black/5'
                              ]">
                                 <ShieldAlert class="h-5 w-5" />
                              </div>
                              <div>
                                 <p class="text-sm font-black text-slate-900 leading-none mb-1 group-hover:underline decoration-red-500/30 underline-offset-4">{{ item.tipo }}</p>
                                 <p class="text-[9px] font-bold text-slate-400 uppercase">TICKET #{{ item.id.toString().padStart(5, '0') }}</p>
                              </div>
                           </div>
                        </td>
                        <td class="px-6 py-5">
                           <span class="text-xs font-black text-slate-900 italic">{{ item.reportado }}</span>
                        </td>
                        <td class="px-6 py-5 text-xs font-bold text-slate-500">{{ item.autor }}</td>
                        <td class="px-6 py-5">
                           <span :class="[
                             item.status === 'resolvido' ? 'bg-green-50 text-green-600 border-green-100' :
                             item.status === 'pendente' ? 'bg-red-50 text-red-600 border-red-100' :
                             'bg-blue-50 text-blue-600 border-blue-100',
                             'px-3 py-1.5 rounded-full text-[8px] font-black uppercase border'
                           ]">
                             {{ item.status }}
                           </span>
                        </td>
                        <td class="px-6 py-5">
                           <div class="flex items-center gap-1.5">
                              <div v-for="i in 3" :key="i" :class="[
                                i <= (item.prioridade === 'alta' ? 3 : item.prioridade === 'media' ? 2 : 1) ?
                                (item.prioridade === 'alta' ? 'bg-red-500' : 'bg-amber-400') : 'bg-slate-100',
                                'h-1.5 w-4 rounded-full'
                              ]" />
                           </div>
                        </td>
                        <td class="px-6 py-5 text-[10px] font-bold text-slate-400">{{ item.data }}</td>
                     </template>

                     <!-- AVALIACOES ROW -->
                     <template v-else-if="activeTab === 'avaliacoes'">
                        <td class="py-5 px-8">
                           <div class="flex items-center gap-3">
                              <div class="flex gap-0.5">
                                 <div v-for="i in 5" :key="i" class="h-2 w-2 rounded-full" :class="i <= item.nota ? 'bg-amber-400' : 'bg-slate-100'" />
                              </div>
                              <p class="text-[11px] font-bold text-slate-500 max-w-[180px] truncate italic">"{{ item.comentario }}"</p>
                           </div>
                        </td>
                        <td class="px-6 py-5 text-xs font-black text-slate-700">{{ item.prestador }}</td>
                        <td class="px-6 py-5 text-xs font-bold text-slate-500">{{ item.cliente }}</td>
                        <td class="px-6 py-5">
                           <span class="px-2 py-1 bg-amber-900 text-white rounded text-[8px] font-black uppercase tracking-tighter shadow-lg shadow-amber-900/10">Sinalizada</span>
                        </td>
                     </template>

                     <td class="px-8 py-5 text-right">
                        <div class="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                           <button @click="handleViewDetails(item)" class="p-2 text-slate-400 hover:text-slate-900 hover:bg-white shadow-sm border border-transparent hover:border-slate-100 rounded-xl transition-all">
                              <Eye class="h-4 w-4" />
                           </button>
                           <template v-if="canPerformAction('edit', 'moderacao')">
                              <!-- Denuncias actions -->
                              <button v-if="activeTab === 'denuncias'" @click="handleAction('suspender_usuario', item)" class="p-2 text-slate-400 hover:text-red-600 hover:bg-white shadow-sm border border-transparent hover:border-slate-100 rounded-xl transition-all" title="Suspender Usuário">
                                 <Ban class="h-4 w-4" />
                              </button>
                              <button v-if="activeTab === 'denuncias'" @click="handleAction('arquivar_denuncia', item)" class="p-2 text-slate-400 hover:text-slate-600 hover:bg-white shadow-sm border border-transparent hover:border-slate-100 rounded-xl transition-all" title="Arquivar">
                                 <Archive class="h-4 w-4" />
                              </button>
                              <!-- Avaliacoes actions -->
                              <button v-if="activeTab === 'avaliacoes'" @click="handleAction('manter_avaliacao', item)" class="p-2 text-slate-400 hover:text-green-600 hover:bg-white shadow-sm border border-transparent hover:border-slate-100 rounded-xl transition-all" title="Manter Avaliação">
                                 <CheckCircle2 class="h-4 w-4" />
                              </button>
                              <button v-if="activeTab === 'avaliacoes'" @click="handleAction('remover_avaliacao', item)" class="p-2 text-slate-400 hover:text-red-600 hover:bg-white shadow-sm border border-transparent hover:border-slate-100 rounded-xl transition-all" title="Remover Avaliação">
                                 <Ban class="h-4 w-4" />
                              </button>
                           </template>
                           <button class="p-2 text-slate-400 hover:text-slate-900 hover:bg-slate-50 rounded-xl transition-all">
                              <MoreVertical class="h-4 w-4" />
                           </button>
                        </div>
                     </td>
                  </tr>
               </tbody>
            </table>
          </div>
        </div>

        <AdminPagination 
          v-if="currentData.length > 0 && activeTab !== 'historico'"
          :current-page="currentPage"
          :total-pages="totalPages"
          :total-items="currentData.length"
          :items-per-page="itemsPerPage"
          @page-change="currentPage = $event"
        />
      </div>
    </div>

    <!-- Mod Modal -->
    <AdminModal :is-open="isModalOpen" @close="isModalOpen = false" :title="`Dossiê de Moderação`" size="lg">
       <div v-if="selectedItem" class="space-y-8">
          <div class="flex items-center gap-6 p-6 bg-slate-50 rounded-[28px]">
             <div :class="[
               selectedItem.prioridade === 'alta' ? 'bg-red-600 text-white shadow-red-600/20' : 'bg-slate-900 text-white shadow-slate-900/20',
               'h-16 w-16 rounded-[22px] flex items-center justify-center shadow-xl'
             ]">
                <component :is="activeTab === 'denuncias' ? ShieldAlert : Flag" class="h-8 w-8" />
             </div>
             <div>
                <h4 class="text-xl font-black text-slate-900 leading-tight">{{ selectedItem.tipo || 'Avaliação Sinalizada' }}</h4>
                <p class="text-xs font-bold text-slate-400">IDENTIFICADOR DE RISCO #{{ selectedItem.id }}</p>
             </div>
          </div>

          <div class="bg-red-50/30 p-8 rounded-[28px] border border-red-100/30">
             <h5 class="text-[10px] font-black text-red-400 uppercase tracking-widest mb-4">Relato e Detalhes Contextuais</h5>
             <p class="text-sm font-black text-slate-900 leading-relaxed italic">"{{ selectedItem.detalhes || selectedItem.comentario }}"</p>
          </div>

          <div class="grid grid-cols-2 gap-x-8 gap-y-6 px-4">
             <div v-for="(val, key) in selectedItem" :key="key">
                <template v-if="!['id', 'type', 'detalhes', 'comentario'].includes(String(key))">
                   <p class="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">{{ String(key).replace(/([A-Z])/g, ' $1') }}</p>
                   <p class="text-sm font-black text-slate-900">{{ val }}</p>
                </template>
             </div>
          </div>

          <div class="flex gap-3 justify-end pt-4 border-t border-slate-50">
             <button @click="isModalOpen = false" class="px-6 py-3 rounded-2xl bg-slate-100 text-slate-600 font-bold text-sm tracking-tight hover:bg-slate-200 transition-all">Manter Registro</button>
             <button @click="handleAction('suspender', selectedItem)" class="px-8 py-3 rounded-2xl bg-red-600 text-white font-black text-sm shadow-xl shadow-red-600/20 hover:bg-red-700 transition-all">Efetivar Suspensão</button>
          </div>
       </div>
    </AdminModal>
  </div>
</template>

<style scoped>
.scrollbar-hide::-webkit-scrollbar { display: none; }
.scrollbar-hide { -ms-overflow-style: none; scrollbar-width: none; }
.animate-in { animation: fadeIn 0.8s cubic-bezier(0.2, 0.8, 0.2, 1); }
@keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
</style>

// pebaspro-master-administrativo/src/pages/Moderacao.tsx
import React, { useState, useMemo } from 'react';
import { Search, Filter, ShieldAlert, AlertTriangle, Flag, UserX, MessageSquare, MoreVertical, Eye, Ban, Archive, RotateCcw, CheckCircle2, History } from 'lucide-react';
import { cn } from '../lib/utils';
import { Modal } from '../components/ui/Modal';
import { Pagination } from '../components/ui/Pagination';
import { EmptyState } from '../components/ui/EmptyState';
import { usePermissions } from '../hooks/usePermissions';
import { useAudit } from '../hooks/useAudit';

const mockDenuncias = Array.from({ length: 45 }, (_, i) => ({
  id: i + 1,
  tipo: i % 3 === 0 ? 'Comportamento Inadequado' : i % 2 === 0 ? 'Vaga Falsa' : 'Perfil Falso',
  reportado: `Usuário Reportado ${i}`,
  autor: `Autor ${i}`,
  status: i % 4 === 0 ? 'resolvido' : i % 3 === 0 ? 'pendente' : 'em_analise',
  prioridade: i % 5 === 0 ? 'alta' : i % 2 === 0 ? 'media' : 'baixa',
  data: `1${i % 9}/04/2026`,
  detalhes: 'Detalhes da denúncia simulados aqui para visualização no modal.'
}));

const mockAvaliacoes = Array.from({ length: 25 }, (_, i) => ({
  id: i + 1,
  prestador: `Prestador ${i}`,
  cliente: `Cliente ${i}`,
  nota: (i % 5) + 1,
  comentario: i % 2 === 0 ? 'Comentário suspeito de spam ou ofensa.' : 'Avaliação muito baixa sem justificativa clara.',
  status: i % 3 === 0 ? 'em_analise' : 'sinalizada',
  data: `1${i % 9}/04/2026`
}));

type TabType = 'denuncias' | 'avaliacoes' | 'historico';

export default function Moderacao() {
  const [searchTerm, setSearchTerm] = useState('');
  const [activeTab, setActiveTab] = useState<TabType>('denuncias');
  const [currentPage, setCurrentPage] = useState(1);
  const [selectedItem, setSelectedItem] = useState<any>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const { canPerformAction } = usePermissions();
  const { logAction } = useAudit();
  const itemsPerPage = 10;

  const tabs = [
    { id: 'denuncias', name: 'Denúncias', icon: ShieldAlert },
    { id: 'avaliacoes', name: 'Avaliações Sinalizadas', icon: Flag },
    { id: 'historico', name: 'Histórico Disciplinar', icon: History },
  ];

  const filteredDenuncias = useMemo(() => {
    return mockDenuncias.filter(d =>
      d.reportado.toLowerCase().includes(searchTerm.toLowerCase()) ||
      d.autor.toLowerCase().includes(searchTerm.toLowerCase()) ||
      d.id.toString().includes(searchTerm)
    );
  }, [searchTerm]);

  const filteredAvaliacoes = useMemo(() => {
    return mockAvaliacoes.filter(a =>
      a.prestador.toLowerCase().includes(searchTerm.toLowerCase()) ||
      a.cliente.toLowerCase().includes(searchTerm.toLowerCase())
    );
  }, [searchTerm]);

  const currentData = activeTab === 'denuncias' ? filteredDenuncias : filteredAvaliacoes;
  const totalPages = Math.ceil(currentData.length / itemsPerPage);
  const paginatedData = currentData.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  const handleViewDetails = (item: any) => {
    setSelectedItem(item);
    setIsModalOpen(true);
    logAction(`view_${activeTab}_details`, 'moderacao', { itemId: item.id });
  };

  const handleAction = (action: string, item?: any) => {
    if (!canPerformAction('edit', 'moderacao')) {
      alert('Você não tem permissão para realizar esta ação.');
      return;
    }
    logAction(`action_${action}_${activeTab}`, 'moderacao', item ? { itemId: item.id } : undefined);
    alert(`Ação "${action}" realizada. (Simulação)`);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-gray-900">Moderação e Confiança</h1>
          <p className="mt-1 text-sm text-gray-500">
            Gerencie denúncias, avaliações sinalizadas e usuários suspensos.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button className="inline-flex items-center gap-2 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
            <Filter className="h-4 w-4 text-gray-500" />
            Filtros Avançados
          </button>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        <div className="overflow-hidden rounded-xl bg-white px-4 py-5 shadow-sm border border-gray-100">
          <dt className="truncate text-sm font-medium text-gray-500">Denúncias Pendentes</dt>
          <dd className="mt-2 text-3xl font-semibold tracking-tight text-gray-900">
            {mockDenuncias.filter(d => d.status === 'pendente').length}
          </dd>
        </div>
        <div className="overflow-hidden rounded-xl bg-white px-4 py-5 shadow-sm border border-gray-100">
          <dt className="truncate text-sm font-medium text-gray-500">Prioridade Alta</dt>
          <dd className="mt-2 text-3xl font-semibold tracking-tight text-red-600">
            {mockDenuncias.filter(d => d.prioridade === 'alta').length}
          </dd>
        </div>
        <div className="overflow-hidden rounded-xl bg-white px-4 py-5 shadow-sm border border-gray-100">
          <dt className="truncate text-sm font-medium text-gray-500">Avaliações em Análise</dt>
          <dd className="mt-2 text-3xl font-semibold tracking-tight text-yellow-600">
            {mockAvaliacoes.filter(a => a.status === 'em_analise').length}
          </dd>
        </div>
        <div className="overflow-hidden rounded-xl bg-white px-4 py-5 shadow-sm border border-gray-100">
          <dt className="truncate text-sm font-medium text-gray-500">Usuários Suspensos</dt>
          <dd className="mt-2 text-3xl font-semibold tracking-tight text-gray-900">156</dd>
        </div>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        {/* Tabs */}
        <div className="border-b border-gray-200">
          <nav className="-mb-px flex space-x-8 overflow-x-auto px-6" aria-label="Tabs">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => {
                  setActiveTab(tab.id as TabType);
                  setCurrentPage(1);
                  setSearchTerm('');
                }}
                className={cn(
                  activeTab === tab.id
                    ? 'border-primary-500 text-primary-600'
                    : 'border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700',
                  'group inline-flex items-center border-b-2 py-4 px-1 text-sm font-medium whitespace-nowrap'
                )}
              >
                <tab.icon
                  className={cn(
                    activeTab === tab.id ? 'text-primary-500' : 'text-gray-400 group-hover:text-gray-500',
                    '-ml-0.5 mr-2 h-5 w-5'
                  )}
                  aria-hidden="true"
                />
                {tab.name}
              </button>
            ))}
          </nav>
        </div>

        {/* Tab Content */}
        <div className="p-0">
          {activeTab === 'denuncias' && (
            <>
              <div className="p-4 border-b border-gray-100 flex flex-col sm:flex-row gap-4 justify-between items-center">
                <div className="relative w-full sm:max-w-md">
                  <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                    <Search className="h-4 w-4 text-gray-400" />
                  </div>
                  <input
                    type="text"
                    className="block w-full rounded-md border-0 py-1.5 pl-10 pr-3 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-primary-600 sm:text-sm sm:leading-6"
                    placeholder="Buscar por usuário ou ID da denúncia..."
                    value={searchTerm}
                    onChange={(e) => {
                      setSearchTerm(e.target.value);
                      setCurrentPage(1);
                    }}
                  />
                </div>
                <div className="flex gap-2 w-full sm:w-auto">
                  <select className="block w-full rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-primary-600 sm:text-sm sm:leading-6">
                    <option>Todas as Prioridades</option>
                    <option>Alta</option>
                    <option>Média</option>
                    <option>Baixa</option>
                  </select>
                </div>
              </div>

              {filteredDenuncias.length === 0 ? (
                <EmptyState
                  title="Nenhuma denúncia encontrada"
                  description={`Não encontramos resultados para "${searchTerm}".`}
                />
              ) : (
                <>
                  <div className="overflow-x-auto">
                    <table className="min-w-full divide-y divide-gray-200">
                      <thead className="bg-gray-50">
                        <tr>
                          <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Denúncia</th>
                          <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Reportado</th>
                          <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Autor</th>
                          <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Status</th>
                          <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Prioridade</th>
                          <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Data</th>
                          <th scope="col" className="relative py-3.5 pl-3 pr-4 sm:pr-6">
                            <span className="sr-only">Ações</span>
                          </th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-200 bg-white">
                        {paginatedData.map((denuncia: any) => (
                          <tr key={denuncia.id} className="hover:bg-gray-50">
                            <td className="whitespace-nowrap py-4 pl-4 pr-3 sm:pl-6">
                              <div className="flex items-center">
                                <div className={`h-10 w-10 flex-shrink-0 rounded-md flex items-center justify-center border ${denuncia.prioridade === 'alta' ? 'bg-red-50 border-red-100 text-red-600' : 'bg-yellow-50 border-yellow-100 text-yellow-600'}`}>
                                  <ShieldAlert className="h-5 w-5" />
                                </div>
                                <div className="ml-4">
                                  <div className="font-medium text-gray-900">{denuncia.tipo}</div>
                                  <div className="text-sm text-gray-500">ID: #{denuncia.id.toString().padStart(4, '0')}</div>
                                </div>
                              </div>
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-900 font-medium">
                              {denuncia.reportado}
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                              {denuncia.autor}
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm">
                              {denuncia.status === 'em_analise' && (
                                <span className="inline-flex items-center rounded-full bg-blue-50 px-2 py-1 text-xs font-medium text-blue-700 ring-1 ring-inset ring-blue-600/20">
                                  Em Análise
                                </span>
                              )}
                              {denuncia.status === 'pendente' && (
                                <span className="inline-flex items-center rounded-full bg-yellow-50 px-2 py-1 text-xs font-medium text-yellow-800 ring-1 ring-inset ring-yellow-600/20">
                                  Pendente
                                </span>
                              )}
                              {denuncia.status === 'resolvido' && (
                                <span className="inline-flex items-center rounded-full bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
                                  Resolvido
                                </span>
                              )}
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm">
                              <span className={`inline-flex items-center gap-1.5 rounded-full px-2 py-1 text-xs font-medium ring-1 ring-inset ${
                                denuncia.prioridade === 'alta' ? 'bg-red-50 text-red-700 ring-red-600/20' :
                                denuncia.prioridade === 'media' ? 'bg-orange-50 text-orange-700 ring-orange-600/20' :
                                'bg-gray-50 text-gray-600 ring-gray-500/10'
                              }`}>
                                {denuncia.prioridade === 'alta' && <AlertTriangle className="h-3 w-3" />}
                                {denuncia.prioridade.charAt(0).toUpperCase() + denuncia.prioridade.slice(1)}
                              </span>
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{denuncia.data}</td>
                            <td className="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                              <div className="flex items-center justify-end gap-2">
                                <button onClick={() => handleViewDetails(denuncia)} className="text-gray-400 hover:text-primary-600" title="Visualizar Detalhes">
                                  <Eye className="h-4 w-4" />
                                </button>
                                {canPerformAction('edit', 'moderacao') && (
                                  <>
                                    <button onClick={() => handleAction('suspender_usuario', denuncia)} className="text-gray-400 hover:text-red-600" title="Suspender Usuário">
                                      <Ban className="h-4 w-4" />
                                    </button>
                                    <button onClick={() => handleAction('arquivar_denuncia', denuncia)} className="text-gray-400 hover:text-gray-600" title="Arquivar">
                                      <Archive className="h-4 w-4" />
                                    </button>
                                  </>
                                )}
                                <button className="text-gray-400 hover:text-gray-600">
                                  <MoreVertical className="h-4 w-4" />
                                </button>
                              </div>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                  <Pagination
                    currentPage={currentPage}
                    totalPages={totalPages}
                    totalItems={filteredDenuncias.length}
                    itemsPerPage={itemsPerPage}
                    onPageChange={setCurrentPage}
                  />
                </>
              )}
            </>
          )}

          {activeTab === 'avaliacoes' && (
            <>
              <div className="p-4 border-b border-gray-100 flex flex-col sm:flex-row gap-4 justify-between items-center">
                <div className="relative w-full sm:max-w-md">
                  <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                    <Search className="h-4 w-4 text-gray-400" />
                  </div>
                  <input
                    type="text"
                    className="block w-full rounded-md border-0 py-1.5 pl-10 pr-3 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-primary-600 sm:text-sm sm:leading-6"
                    placeholder="Buscar por prestador ou cliente..."
                    value={searchTerm}
                    onChange={(e) => {
                      setSearchTerm(e.target.value);
                      setCurrentPage(1);
                    }}
                  />
                </div>
              </div>

              {filteredAvaliacoes.length === 0 ? (
                <EmptyState
                  title="Nenhuma avaliação encontrada"
                  description={`Não encontramos resultados para "${searchTerm}".`}
                />
              ) : (
                <>
                  <div className="overflow-x-auto">
                    <table className="min-w-full divide-y divide-gray-200">
                      <thead className="bg-gray-50">
                        <tr>
                          <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Avaliação</th>
                          <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Prestador</th>
                          <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Cliente</th>
                          <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Status</th>
                          <th scope="col" className="relative py-3.5 pl-3 pr-4 sm:pr-6">
                            <span className="sr-only">Ações</span>
                          </th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-200 bg-white">
                        {paginatedData.map((avaliacao: any) => (
                          <tr key={avaliacao.id} className="hover:bg-gray-50">
                            <td className="py-4 pl-4 pr-3 sm:pl-6">
                              <div className="font-medium text-gray-900">Nota: {avaliacao.nota}/5</div>
                              <div className="text-sm text-gray-500 max-w-xs truncate">{avaliacao.comentario}</div>
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-900">{avaliacao.prestador}</td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{avaliacao.cliente}</td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm">
                              <span className="inline-flex items-center rounded-full bg-yellow-50 px-2 py-1 text-xs font-medium text-yellow-800 ring-1 ring-inset ring-yellow-600/20">
                                {avaliacao.status.replace('_', ' ')}
                              </span>
                            </td>
                            <td className="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                              <div className="flex items-center justify-end gap-2">
                                <button onClick={() => handleViewDetails(avaliacao)} className="text-gray-400 hover:text-primary-600" title="Ver Detalhes">
                                  <Eye className="h-4 w-4" />
                                </button>
                                {canPerformAction('edit', 'moderacao') && (
                                  <>
                                    <button onClick={() => handleAction('manter_avaliacao', avaliacao)} className="text-gray-400 hover:text-green-600" title="Manter Avaliação">
                                      <CheckCircle2 className="h-4 w-4" />
                                    </button>
                                    <button onClick={() => handleAction('remover_avaliacao', avaliacao)} className="text-gray-400 hover:text-red-600" title="Remover Avaliação">
                                      <Ban className="h-4 w-4" />
                                    </button>
                                  </>
                                )}
                              </div>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                  <Pagination
                    currentPage={currentPage}
                    totalPages={totalPages}
                    totalItems={filteredAvaliacoes.length}
                    itemsPerPage={itemsPerPage}
                    onPageChange={setCurrentPage}
                  />
                </>
              )}
            </>
          )}

          {activeTab === 'historico' && (
            <div className="p-6 text-center text-gray-500">
              <History className="mx-auto h-12 w-12 text-gray-300 mb-4" />
              <h3 className="text-lg font-medium text-gray-900">Histórico Disciplinar</h3>
              <p className="mt-1">Busque por um usuário para ver seu histórico de advertências e suspensões.</p>
            </div>
          )}
        </div>
      </div>

      <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title={`Detalhes da ${activeTab === 'denuncias' ? 'Denúncia' : 'Avaliação'}`}>
        {selectedItem && (
          <div className="space-y-4">
            {activeTab === 'denuncias' ? (
              <>
                <div className="flex items-center gap-4 border-b border-gray-100 pb-4">
                  <div className={`h-16 w-16 rounded-md flex items-center justify-center border ${selectedItem.prioridade === 'alta' ? 'bg-red-50 border-red-100 text-red-600' : 'bg-yellow-50 border-yellow-100 text-yellow-600'}`}>
                    <ShieldAlert className="h-8 w-8" />
                  </div>
                  <div>
                    <h3 className="text-lg font-medium text-gray-900">{selectedItem.tipo}</h3>
                    <p className="text-sm text-gray-500">ID: #{selectedItem.id.toString().padStart(4, '0')}</p>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-sm font-medium text-gray-500">Reportado</p>
                    <p className="mt-1 text-sm text-gray-900">{selectedItem.reportado}</p>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-gray-500">Autor</p>
                    <p className="mt-1 text-sm text-gray-900">{selectedItem.autor}</p>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-gray-500">Status</p>
                    <p className="mt-1 text-sm text-gray-900 capitalize">{selectedItem.status.replace('_', ' ')}</p>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-gray-500">Prioridade</p>
                    <p className="mt-1 text-sm text-gray-900 capitalize">{selectedItem.prioridade}</p>
                  </div>
                </div>
                <div>
                  <p className="text-sm font-medium text-gray-500">Detalhes</p>
                  <p className="mt-1 text-sm text-gray-900 bg-gray-50 p-3 rounded-md border border-gray-100">{selectedItem.detalhes}</p>
                </div>
              </>
            ) : (
              <>
                <div className="flex items-center gap-4 border-b border-gray-100 pb-4">
                  <div className="h-16 w-16 rounded-md bg-yellow-50 flex items-center justify-center border border-yellow-100 text-yellow-600">
                    <Flag className="h-8 w-8" />
                  </div>
                  <div>
                    <h3 className="text-lg font-medium text-gray-900">Avaliação Sinalizada</h3>
                    <p className="text-sm text-gray-500">Nota: {selectedItem.nota}/5</p>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-sm font-medium text-gray-500">Prestador</p>
                    <p className="mt-1 text-sm text-gray-900">{selectedItem.prestador}</p>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-gray-500">Cliente</p>
                    <p className="mt-1 text-sm text-gray-900">{selectedItem.cliente}</p>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-gray-500">Status</p>
                    <p className="mt-1 text-sm text-gray-900 capitalize">{selectedItem.status.replace('_', ' ')}</p>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-gray-500">Data</p>
                    <p className="mt-1 text-sm text-gray-900">{selectedItem.data}</p>
                  </div>
                </div>
                <div>
                  <p className="text-sm font-medium text-gray-500">Comentário</p>
                  <p className="mt-1 text-sm text-gray-900 bg-gray-50 p-3 rounded-md border border-gray-100">{selectedItem.comentario}</p>
                </div>
              </>
            )}
            <div className="mt-6 flex justify-end gap-3">
              <button onClick={() => setIsModalOpen(false)} className="rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
                Fechar
              </button>
              {canPerformAction('edit', 'moderacao') && (
                <button onClick={() => { handleAction(activeTab === 'denuncias' ? 'resolver_denuncia' : 'remover_avaliacao', selectedItem); setIsModalOpen(false); }} className="rounded-md bg-primary-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-primary-500">
                  {activeTab === 'denuncias' ? 'Marcar como Resolvido' : 'Remover Avaliação'}
                </button>
              )}
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}
