// app/pages/admin/servicos.vue
<script setup lang="ts">
import { 
  Search, 
  Filter, 
  CalendarCheck, 
  Clock, 
  CheckCircle2, 
  XCircle, 
  AlertTriangle, 
  MoreVertical, 
  UserCircle, 
  Eye, 
  MessageSquare, 
  Ban, 
  CalendarDays 
} from 'lucide-vue-next'
import { useAdminPermissions } from '~/composables/useAdminPermissions'
import { useAdminAudit } from '~/composables/useAdminAudit'

definePageMeta({
  layout: 'admin-master',
  middleware: 'admin'
})

const { canPerformAction } = useAdminPermissions()
const { logAction } = useAdminAudit()

// UI State
const searchTerm = ref('')
const currentPage = ref(1)
const isLoading = ref(true)
const selectedItem = ref<any>(null)
const isModalOpen = ref(false)
const itemsPerPage = 8

// Mock Data
const mockServicos = ref(Array.from({ length: 45 }, (_, i) => ({
  id: i + 1,
  titulo: i % 3 === 0 ? 'Manutenção Elétrica' : i % 2 === 0 ? 'Limpeza Pós-Obra' : 'Instalação Hidráulica',
  prestador: `Prestador ${i}`,
  cliente: `Cliente ${i}`,
  status: i % 5 === 0 ? 'disputa' : i % 4 === 0 ? 'concluido' : i % 3 === 0 ? 'em_andamento' : 'agendado',
  valor: `R$ ${(Math.random() * 800 + 100).toFixed(2).replace('.', ',')}`,
  data: `1${i % 9}/04/2026`,
})))

// Simulate loading
onMounted(() => {
  setTimeout(() => {
    isLoading.value = false
  }, 500)
})

// Filter logic
const filteredServicos = computed(() => {
  return mockServicos.value.filter(s => 
    s.titulo.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
    s.prestador.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
    s.cliente.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
    s.id.toString().includes(searchTerm.value)
  )
})

// Pagination logic
const totalPages = computed(() => Math.ceil(filteredServicos.value.length / itemsPerPage))
const paginatedData = computed(() => {
  const start = (currentPage.value - 1) * itemsPerPage
  return filteredServicos.value.slice(start, start + itemsPerPage)
})

watch(searchTerm, () => {
  currentPage.value = 1
})

const handleViewDetails = (item: any) => {
  selectedItem.value = item
  isModalOpen.value = true
  logAction('view_service_details', 'servicos', { serviceId: item.id })
}

const handleAction = (action: string, item?: any) => {
  if (!canPerformAction('edit', 'servicos')) {
    alert('Você não tem permissão para realizar esta ação.')
    return
  }
  logAction(`action_${action}_servico`, 'servicos', item ? { serviceId: item.id } : undefined)
  alert(`Ação "${action}" realizada com sucesso!`)
}

// Stats computed
const stats = computed(() => ([
  { label: 'Em Andamento', value: mockServicos.value.filter(s => s.status === 'em_andamento').length, color: 'text-amber-600' },
  { label: 'Próximos 7 dias', value: mockServicos.value.filter(s => s.status === 'agendado').length, color: 'text-blue-600' },
  { label: 'Concluídos Mês', value: mockServicos.value.filter(s => s.status === 'concluido').length, color: 'text-green-600' },
  { label: 'Em Disputa', value: mockServicos.value.filter(s => s.status === 'disputa').length, color: 'text-red-600' }
]))
</script>

<template>
  <div class="space-y-8 animate-in fade-in duration-700">
    <!-- Header -->
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
      <div>
        <h1 class="text-3xl font-black text-slate-900 tracking-tight">Serviços & Agenda</h1>
        <p class="text-slate-500 font-medium mt-1">Supervisão de fluxos operacionais e mediação de conflitos.</p>
      </div>
    </div>

    <!-- Stats Grid -->
    <div class="grid grid-cols-2 lg:grid-cols-4 gap-6">
       <div v-for="stat in stats" :key="stat.label" class="p-6 bg-white rounded-[28px] border border-slate-100 shadow-sm hover:shadow-md transition-all">
          <p class="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">{{ stat.label }}</p>
          <div class="flex items-end justify-between">
            <h3 class="text-3xl font-black" :class="stat.color">{{ stat.value }}</h3>
            <div class="h-8 w-8 rounded-lg bg-slate-50 flex items-center justify-center">
               <component :is="stat.label === 'Em Disputa' ? AlertTriangle : Clock" class="h-4 w-4 text-slate-300" />
            </div>
          </div>
       </div>
    </div>

    <!-- Controls -->
    <div class="flex flex-col md:flex-row gap-4 items-center justify-between bg-white p-6 rounded-[32px] shadow-sm border border-slate-100">
      <div class="relative w-full max-w-md">
        <Search class="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
        <input
          v-model="searchTerm"
          type="text"
          class="block w-full rounded-2xl border-slate-100 bg-slate-50/50 pl-11 pr-4 py-3 text-sm font-bold text-slate-900 placeholder:text-slate-400 focus:ring-green-500 focus:border-green-500 transition-all"
          placeholder="Filtrar por ID, título, prestador ou cliente..."
        />
      </div>
      <div class="flex gap-3">
        <select class="rounded-2xl border-slate-100 bg-white py-3 pl-4 pr-10 text-sm font-bold text-slate-700 shadow-sm cursor-pointer transition-all focus:ring-green-500">
          <option>Fluxo Completo</option>
          <option>Agendado</option>
          <option>Em Andamento</option>
          <option>Concluído</option>
          <option>Em Disputa</option>
        </select>
        <button class="flex items-center gap-2 rounded-2xl bg-slate-900 px-5 py-3 text-sm font-black text-white hover:bg-slate-800 transition-all shadow-lg shadow-slate-900/10">
          <Filter class="h-4 w-4" />
          Filtros
        </button>
      </div>
    </div>

    <!-- Data Table -->
    <div class="bg-white rounded-[32px] shadow-sm border border-slate-100 overflow-hidden">
      <div v-if="isLoading" class="p-20 text-center">
        <div class="animate-spin h-10 w-10 border-4 border-indigo-500 border-t-transparent rounded-full mx-auto mb-4"></div>
        <p class="text-slate-400 font-black uppercase tracking-widest text-xs">Mapeando Agenda Global...</p>
      </div>

      <AdminEmptyState 
        v-else-if="filteredServicos.length === 0"
        title="Nenhum ciclo operacional encontrado" 
        :description="`Refine sua busca para '${searchTerm}' ou altere os filtros de status.`"
      />

      <div v-else>
        <div class="overflow-x-auto">
          <table class="min-w-full divide-y divide-slate-50">
            <thead class="bg-slate-50/50">
              <tr>
                <th class="py-5 px-8 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Serviço / ID</th>
                <th class="px-6 py-5 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Stakeholders</th>
                <th class="px-6 py-5 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Status Atual</th>
                <th class="px-6 py-5 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">Valor Brut.</th>
                <th class="px-6 py-5 text-right text-[10px] font-black text-slate-400 uppercase tracking-widest">Ações</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-slate-50">
              <tr v-for="servico in paginatedData" :key="servico.id" class="group hover:bg-slate-50/50 transition-colors">
                <td class="whitespace-nowrap py-5 px-8">
                  <div class="flex items-center">
                    <div class="h-10 w-10 rounded-xl bg-indigo-50 flex items-center justify-center text-indigo-600 group-hover:bg-indigo-600 group-hover:text-white transition-all">
                      <CalendarCheck class="h-5 w-5" />
                    </div>
                    <div class="ml-4">
                      <div class="text-sm font-black text-slate-900 tracking-tight">{{ servico.titulo }}</div>
                      <div class="text-[9px] font-black text-slate-400 uppercase">Track ID #{{ servico.id.toString().padStart(5, '0') }}</div>
                    </div>
                  </div>
                </td>
                <td class="whitespace-nowrap px-6 py-5">
                   <div class="flex flex-col gap-1">
                      <div class="flex items-center gap-2 text-[11px] font-bold text-slate-600">
                         <div class="h-1.5 w-1.5 rounded-full bg-blue-500" />
                         P: {{ servico.prestador }}
                      </div>
                      <div class="flex items-center gap-2 text-[11px] font-bold text-slate-600">
                         <div class="h-1.5 w-1.5 rounded-full bg-slate-300" />
                         C: {{ servico.cliente }}
                      </div>
                   </div>
                </td>
                <td class="whitespace-nowrap px-6 py-5">
                  <span v-if="servico.status === 'concluido'" class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[9px] font-black uppercase bg-green-50 text-green-600 ring-1 ring-green-600/10">
                    <CheckCircle2 class="h-3.5 w-3.5" /> Concluído
                  </span>
                  <span v-else-if="servico.status === 'agendado'" class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[9px] font-black uppercase bg-blue-50 text-blue-600 ring-1 ring-blue-600/10">
                    <Clock class="h-3.5 w-3.5" /> Agendado
                  </span>
                  <span v-else-if="servico.status === 'em_andamento'" class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[9px] font-black uppercase bg-amber-50 text-amber-600 ring-1 ring-amber-600/10">
                    <Clock class="h-3.5 w-3.5" /> Executando
                  </span>
                  <span v-else class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[9px] font-black uppercase bg-red-50 text-red-600 ring-1 ring-red-600/10">
                    <AlertTriangle class="h-3.5 w-3.5" /> Em Disputa
                  </span>
                </td>
                <td class="whitespace-nowrap px-6 py-5 text-sm font-black text-slate-900 italic">
                  {{ servico.valor }}
                </td>
                <td class="whitespace-nowrap px-8 py-5 text-right">
                  <div class="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button @click="handleViewDetails(servico)" class="p-2 text-slate-400 hover:text-indigo-600 hover:bg-white shadow-sm border border-transparent hover:border-slate-100 rounded-xl transition-all">
                      <Eye class="h-4 w-4" />
                    </button>
                    <template v-if="canPerformAction('edit', 'servicos')">
                      <button v-if="servico.status === 'disputa'" @click="handleAction('mediar', servico)" class="p-2 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-xl transition-all" title="Mediar Conflito">
                        <MessageSquare class="h-4 w-4" />
                      </button>
                      <button v-if="servico.status === 'agendado'" @click="handleAction('cancelar', servico)" class="p-2 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-xl transition-all" title="Cancelar">
                        <Ban class="h-4 w-4" />
                      </button>
                    </template>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <AdminPagination 
          :current-page="currentPage" 
          :total-pages="totalPages" 
          :total-items="filteredServicos.length" 
          :items-per-page="itemsPerPage" 
          @page-change="currentPage = $event"
        />
      </div>
    </div>

    <!-- Details Modal -->
    <AdminModal :is-open="isModalOpen" @close="isModalOpen = false" title="Ciclo Operacional Detalhado">
      <div v-if="selectedItem" class="space-y-8">
        <div class="flex items-center gap-6 p-6 bg-slate-50 rounded-[28px]">
          <div class="h-20 w-20 rounded-[24px] bg-white flex items-center justify-center text-indigo-600 shadow-xl shadow-slate-200/50">
            <CalendarCheck class="h-10 w-10" />
          </div>
          <div>
            <h3 class="text-2xl font-black text-slate-900 tracking-tight">{{ selectedItem.titulo }}</h3>
            <p class="text-slate-500 font-bold uppercase tracking-widest text-[10px]">Identificador Logístico: #{{ selectedItem.id }}</p>
          </div>
        </div>
        
        <div class="grid grid-cols-2 gap-8 px-2">
          <div v-for="info in [
            { label: 'Prestador de Serviço', value: selectedItem.prestador },
            { label: 'Contratante / Cliente', value: selectedItem.cliente },
            { label: 'Status Operacional', value: selectedItem.status, color: true },
            { label: 'Valor da Transação', value: selectedItem.valor },
            { label: 'Data do Evento', value: selectedItem.data }
          ]" :key="info.label">
            <p class="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">{{ info.label }}</p>
            <p class="text-sm font-black text-slate-900" :class="{ 'text-red-600 uppercase': info.color && selectedItem.status === 'disputa' }">
              {{ info.value }}
            </p>
          </div>
        </div>

        <div class="pt-6 border-t border-slate-50 flex justify-end gap-3">
          <button @click="isModalOpen = false" class="rounded-2xl bg-slate-100 px-6 py-3 text-sm font-black text-slate-600 hover:bg-slate-200 transition-all">
            Voltar
          </button>
          <button v-if="canPerformAction('edit', 'servicos') && selectedItem.status === 'disputa'" class="rounded-2xl bg-red-600 px-8 py-3 text-sm font-black text-white shadow-xl shadow-red-600/20 hover:bg-red-700 transition-all">
             Intervir em Disputa
          </button>
        </div>
      </div>
    </AdminModal>
  </div>
</template>

// pebaspro-master-administrativo/src/pages/Servicos.tsx
import React, { useState, useMemo } from 'react';
import { Search, Filter, CalendarCheck, Clock, CheckCircle2, XCircle, AlertTriangle, MoreVertical, UserCircle, Eye, MessageSquare, Ban, CalendarDays } from 'lucide-react';
import { Modal } from '../components/ui/Modal';
import { Pagination } from '../components/ui/Pagination';
import { EmptyState } from '../components/ui/EmptyState';
import { usePermissions } from '../hooks/usePermissions';
import { useAudit } from '../hooks/useAudit';

const mockServicos = Array.from({ length: 45 }, (_, i) => ({
  id: i + 1,
  titulo: i % 3 === 0 ? 'Manutenção Elétrica' : i % 2 === 0 ? 'Limpeza Pós-Obra' : 'Instalação Hidráulica',
  prestador: `Prestador ${i}`,
  cliente: `Cliente ${i}`,
  status: i % 5 === 0 ? 'disputa' : i % 4 === 0 ? 'concluido' : i % 3 === 0 ? 'em_andamento' : 'agendado',
  valor: `R$ ${(Math.random() * 800 + 100).toFixed(2).replace('.', ',')}`,
  data: `1${i % 9}/04/2026`,
}));

export default function Servicos() {
  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [selectedItem, setSelectedItem] = useState<any>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const { canPerformAction } = usePermissions();
  const { logAction } = useAudit();
  const itemsPerPage = 10;

  const filteredServicos = useMemo(() => {
    return mockServicos.filter(s =>
      s.titulo.toLowerCase().includes(searchTerm.toLowerCase()) ||
      s.prestador.toLowerCase().includes(searchTerm.toLowerCase()) ||
      s.cliente.toLowerCase().includes(searchTerm.toLowerCase()) ||
      s.id.toString().includes(searchTerm)
    );
  }, [searchTerm]);

  const totalPages = Math.ceil(filteredServicos.length / itemsPerPage);
  const paginatedData = filteredServicos.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  const handleViewDetails = (item: any) => {
    setSelectedItem(item);
    setIsModalOpen(true);
    logAction('view_service_details', 'servicos', { serviceId: item.id });
  };

  const handleAction = (action: string, item?: any) => {
    if (!canPerformAction('edit', 'servicos')) {
      alert('Você não tem permissão para realizar esta ação.');
      return;
    }
    logAction(`action_${action}_servico`, 'servicos', item ? { serviceId: item.id } : undefined);
    alert(`Ação "${action}" realizada. (Simulação)`);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-gray-900">Serviços & Agenda</h1>
          <p className="mt-1 text-sm text-gray-500">
            Acompanhe os serviços prestados, agendamentos e resolva disputas.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button className="inline-flex items-center gap-2 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
            <Filter className="h-4 w-4 text-gray-500" />
            Filtros Avançados
          </button>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        <div className="overflow-hidden rounded-xl bg-white px-4 py-5 shadow-sm border border-gray-100">
          <dt className="truncate text-sm font-medium text-gray-500">Serviços Ativos</dt>
          <dd className="mt-2 text-3xl font-semibold tracking-tight text-gray-900">
            {mockServicos.filter(s => s.status === 'em_andamento').length}
          </dd>
        </div>
        <div className="overflow-hidden rounded-xl bg-white px-4 py-5 shadow-sm border border-gray-100">
          <dt className="truncate text-sm font-medium text-gray-500">Agendados (Próx 7 dias)</dt>
          <dd className="mt-2 text-3xl font-semibold tracking-tight text-blue-600">
            {mockServicos.filter(s => s.status === 'agendado').length}
          </dd>
        </div>
        <div className="overflow-hidden rounded-xl bg-white px-4 py-5 shadow-sm border border-gray-100">
          <dt className="truncate text-sm font-medium text-gray-500">Concluídos (Mês)</dt>
          <dd className="mt-2 text-3xl font-semibold tracking-tight text-green-600">
            {mockServicos.filter(s => s.status === 'concluido').length}
          </dd>
        </div>
        <div className="overflow-hidden rounded-xl bg-white px-4 py-5 shadow-sm border border-gray-100">
          <dt className="truncate text-sm font-medium text-gray-500">Em Disputa</dt>
          <dd className="mt-2 text-3xl font-semibold tracking-tight text-red-600">
            {mockServicos.filter(s => s.status === 'disputa').length}
          </dd>
        </div>
      </div>

      <div className="flex flex-col sm:flex-row gap-4 items-center justify-between bg-white p-4 rounded-xl shadow-sm border border-gray-100">
        <div className="relative w-full sm:max-w-md">
          <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
            <Search className="h-4 w-4 text-gray-400" />
          </div>
          <input
            type="text"
            className="block w-full rounded-md border-0 py-1.5 pl-10 pr-3 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary-600 sm:text-sm sm:leading-6"
            placeholder="Buscar por ID, título, prestador ou cliente..."
            value={searchTerm}
            onChange={(e) => {
              setSearchTerm(e.target.value);
              setCurrentPage(1);
            }}
          />
        </div>
        <div className="flex gap-2 w-full sm:w-auto">
          <select className="block w-full rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-primary-600 sm:text-sm sm:leading-6">
            <option>Todos os Status</option>
            <option>Agendado</option>
            <option>Em Andamento</option>
            <option>Concluído</option>
            <option>Em Disputa</option>
          </select>
        </div>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        {filteredServicos.length === 0 ? (
          <EmptyState
            title="Nenhum serviço encontrado"
            description={`Não encontramos resultados para "${searchTerm}".`}
          />
        ) : (
          <>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Serviço</th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Prestador</th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Cliente</th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Status</th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Valor</th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Data</th>
                    <th scope="col" className="relative py-3.5 pl-3 pr-4 sm:pr-6">
                      <span className="sr-only">Ações</span>
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200 bg-white">
                  {paginatedData.map((servico) => (
                    <tr key={servico.id} className="hover:bg-gray-50">
                      <td className="whitespace-nowrap py-4 pl-4 pr-3 sm:pl-6">
                        <div className="flex items-center">
                          <div className="h-10 w-10 flex-shrink-0 rounded-md bg-indigo-50 flex items-center justify-center border border-indigo-100">
                            <CalendarCheck className="h-5 w-5 text-indigo-600" />
                          </div>
                          <div className="ml-4">
                            <div className="font-medium text-gray-900">{servico.titulo}</div>
                            <div className="text-sm text-gray-500">ID: #{servico.id.toString().padStart(4, '0')}</div>
                          </div>
                        </div>
                      </td>
                      <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                        <div className="flex items-center gap-1.5">
                          <UserCircle className="h-4 w-4 text-gray-400" />
                          {servico.prestador}
                        </div>
                      </td>
                      <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                        {servico.cliente}
                      </td>
                      <td className="whitespace-nowrap px-3 py-4 text-sm">
                        {servico.status === 'concluido' && (
                          <span className="inline-flex items-center gap-1.5 rounded-full bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
                            <CheckCircle2 className="h-3.5 w-3.5" />
                            Concluído
                          </span>
                        )}
                        {servico.status === 'agendado' && (
                          <span className="inline-flex items-center gap-1.5 rounded-full bg-blue-50 px-2 py-1 text-xs font-medium text-blue-700 ring-1 ring-inset ring-blue-600/20">
                            <Clock className="h-3.5 w-3.5" />
                            Agendado
                          </span>
                        )}
                        {servico.status === 'em_andamento' && (
                          <span className="inline-flex items-center gap-1.5 rounded-full bg-yellow-50 px-2 py-1 text-xs font-medium text-yellow-800 ring-1 ring-inset ring-yellow-600/20">
                            <Clock className="h-3.5 w-3.5" />
                            Em Andamento
                          </span>
                        )}
                        {servico.status === 'disputa' && (
                          <span className="inline-flex items-center gap-1.5 rounded-full bg-red-50 px-2 py-1 text-xs font-medium text-red-700 ring-1 ring-inset ring-red-600/10">
                            <AlertTriangle className="h-3.5 w-3.5" />
                            Em Disputa
                          </span>
                        )}
                      </td>
                      <td className="whitespace-nowrap px-3 py-4 text-sm font-medium text-gray-900">
                        {servico.valor}
                      </td>
                      <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{servico.data}</td>
                      <td className="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                        <div className="flex items-center justify-end gap-2">
                          <button onClick={() => handleViewDetails(servico)} className="text-gray-400 hover:text-primary-600" title="Ver Detalhes">
                            <Eye className="h-4 w-4" />
                          </button>
                          {canPerformAction('edit', 'servicos') && (
                            <>
                              {servico.status === 'disputa' && (
                                <button onClick={() => handleAction('mediar_disputa', servico)} className="text-gray-400 hover:text-red-600" title="Mediar Disputa">
                                  <MessageSquare className="h-4 w-4" />
                                </button>
                              )}
                              {servico.status === 'agendado' && (
                                <>
                                  <button onClick={() => handleAction('remarcar_servico', servico)} className="text-gray-400 hover:text-blue-600" title="Remarcar">
                                    <CalendarDays className="h-4 w-4" />
                                  </button>
                                  <button onClick={() => handleAction('cancelar_servico', servico)} className="text-gray-400 hover:text-red-600" title="Cancelar Serviço">
                                    <Ban className="h-4 w-4" />
                                  </button>
                                </>
                              )}
                            </>
                          )}
                          <button className="text-gray-400 hover:text-gray-600">
                            <MoreVertical className="h-4 w-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <Pagination
              currentPage={currentPage}
              totalPages={totalPages}
              totalItems={filteredServicos.length}
              itemsPerPage={itemsPerPage}
              onPageChange={setCurrentPage}
            />
          </>
        )}
      </div>

      <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title="Detalhes do Serviço">
        {selectedItem && (
          <div className="space-y-4">
            <div className="flex items-center gap-4 border-b border-gray-100 pb-4">
              <div className="h-16 w-16 rounded-md bg-indigo-50 flex items-center justify-center border border-indigo-100">
                <CalendarCheck className="h-8 w-8 text-indigo-600" />
              </div>
              <div>
                <h3 className="text-lg font-medium text-gray-900">{selectedItem.titulo}</h3>
                <p className="text-sm text-gray-500">ID: #{selectedItem.id.toString().padStart(4, '0')}</p>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-sm font-medium text-gray-500">Prestador</p>
                <p className="mt-1 text-sm text-gray-900">{selectedItem.prestador}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-500">Cliente</p>
                <p className="mt-1 text-sm text-gray-900">{selectedItem.cliente}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-500">Status</p>
                <p className="mt-1 text-sm text-gray-900 capitalize">{selectedItem.status.replace('_', ' ')}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-500">Valor</p>
                <p className="mt-1 text-sm text-gray-900">{selectedItem.valor}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-500">Data</p>
                <p className="mt-1 text-sm text-gray-900">{selectedItem.data}</p>
              </div>
            </div>
            <div className="mt-6 flex justify-end gap-3">
              <button onClick={() => setIsModalOpen(false)} className="rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
                Fechar
              </button>
              {canPerformAction('edit', 'servicos') && selectedItem.status === 'disputa' && (
                <button onClick={() => { handleAction('mediar_disputa', selectedItem); setIsModalOpen(false); }} className="rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500">
                  Mediar Disputa
                </button>
              )}
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}
